In [1]:
import optuna

In [2]:
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import pandas as pd

# Load the Pima Indian Diabetes dataset (from UCI repository)
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI',
           'DiabetesPedigreeFunction', 'Age', 'Outcome']

# Load the dataset
df = pd.read_csv(url, names=columns)

df.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [3]:
import numpy as np

cols_with_missing_vals = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_missing_vals] = df[cols_with_missing_vals].replace(0, np.nan)

df.fillna(df.mean(), inplace=True)

print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
# Split into features (X) and target (y)
X = df.drop('Outcome', axis=1)
y = df['Outcome']

# Split data into training and test sets (70% train, 30% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Optional: Scale the data for better model performance
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Check the shape of the data
print(f'Training set shape: {X_train.shape}')
print(f'Test set shape: {X_test.shape}')

Training set shape: (537, 8)
Test set shape: (231, 8)

In [6]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [7]:
# Create a study object and optimize the objective function
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2025-06-10 11:06:25,415] A new study created in memory with name: no-name-79e9f917-f05b-4385-ba74-294f766a707d
[I 2025-06-10 11:06:26,308] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 89, 'max_depth': 15}. Best is trial 0 with value: 0.7690875232774674.
[I 2025-06-10 11:06:28,148] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 136, 'max_depth': 6}. Best is trial 0 with value: 0.7690875232774674.
[I 2025-06-10 11:06:30,173] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 141, 'max_depth': 12}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-10 11:06:30,974] Trial 3 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 90, 'max_depth': 3}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-10 11:06:31,724] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 77, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-10 11:06:32,765] Trial 5 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 92, 'max_depth': 17}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-10 11:06:34,127] Trial 6 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 129, 'max_depth': 13}. Best is trial 6 with value: 0.7746741154562384.
[I 2025-06-10 11:06:35,171] Trial 7 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 111, 'max_depth': 16}. Best is trial 7 with value: 0.7783985102420856.
[I 2025-06-10 11:06:36,232] Trial 8 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 102, 'max_depth': 12}. Best is trial 7 with value: 0.7783985102420856.
[I 2025-06-10 11:06:38,006] Trial 9 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 126, 'max_depth': 16}. Best is trial 9 with value: 0.7802607076350093.
[I 2025-06-10 11:06:40,585] Trial 10 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 192, 'max_depth': 20}. Best is trial 9 with value: 0.7802607076350093.
[I 2025-06-10 11:06:42,524] Trial 11 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 180, 'max_depth': 18}. Best is trial 9 with value: 0.7802607076350093.
[I 2025-06-10 11:06:43,120] Trial 12 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 51, 'max_depth': 16}. Best is trial 9 with value: 0.7802607076350093.
[I 2025-06-10 11:06:46,305] Trial 13 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 158, 'max_depth': 8}. Best is trial 9 with value: 0.7802607076350093.
[I 2025-06-10 11:06:48,517] Trial 14 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 113, 'max_depth': 9}. Best is trial 9 with value: 0.7802607076350093.
[I 2025-06-10 11:06:50,406] Trial 15 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 159, 'max_depth': 20}. Best is trial 9 with value: 0.7802607076350093.
[I 2025-06-10 11:06:51,829] Trial 16 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 115, 'max_depth': 14}. Best is trial 9 with value: 0.7802607076350093.
[I 2025-06-10 11:06:53,959] Trial 17 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 163, 'max_depth': 10}. Best is trial 9 with value: 0.7802607076350093.
[I 2025-06-10 11:06:55,559] Trial 18 finished with value: 0.7802607076350094 and parameters: {'n_estimators': 70, 'max_depth': 17}. Best is trial 18 with value: 0.7802607076350094.
[I 2025-06-10 11:06:56,726] Trial 19 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 56, 'max_depth': 18}. Best is trial 18 with value: 0.7802607076350094.
[I 2025-06-10 11:06:57,593] Trial 20 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 70, 'max_depth': 14}. Best is trial 18 with value: 0.7802607076350094.
[I 2025-06-10 11:06:58,694] Trial 21 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 112, 'max_depth': 16}. Best is trial 18 with value: 0.7802607076350094.
[I 2025-06-10 11:07:00,308] Trial 22 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 145, 'max_depth': 18}. Best is trial 18 with value: 0.7802607076350094.
[I 2025-06-10 11:07:01,440] Trial 23 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 72, 'max_depth': 16}. Best is trial 18 with value: 0.7802607076350094.
[I 2025-06-10 11:07:03,227] Trial 24 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 122, 'max_depth': 19}. Best is trial 18 with value: 0.7802607076350094.
[I 2025-06-10 11:07:04,249] Trial 25 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 98, 'max_depth': 14}. Best is trial 18 with value: 0.7802607076350094.
[I 2025-06-10 11:07:04,893] Trial 26 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 61, 'max_depth': 11}. Best is trial 18 with value: 0.7802607076350094.
[I 2025-06-10 11:07:06,161] Trial 27 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 82, 'max_depth': 17}. Best is trial 18 with value: 0.7802607076350094.
[I 2025-06-10 11:07:08,046] Trial 28 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 127, 'max_depth': 15}. Best is trial 18 with value: 0.7802607076350094.
[I 2025-06-10 11:07:09,268] Trial 29 finished with value: 0.7821229050279329 and parameters: {'n_estimators': 107, 'max_depth': 15}. Best is trial 29 with value: 0.7821229050279329.
[I 2025-06-10 11:07:10,354] Trial 30 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 100, 'max_depth': 13}. Best is trial 29 with value: 0.7821229050279329.
[I 2025-06-10 11:07:11,588] Trial 31 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 113, 'max_depth': 15}. Best is trial 29 with value: 0.7821229050279329.
[I 2025-06-10 11:07:13,226] Trial 32 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 149, 'max_depth': 17}. Best is trial 29 with value: 0.7821229050279329.
[I 2025-06-10 11:07:14,734] Trial 33 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 105, 'max_depth': 19}. Best is trial 29 with value: 0.7821229050279329.
[I 2025-06-10 11:07:16,089] Trial 34 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 136, 'max_depth': 15}. Best is trial 29 with value: 0.7821229050279329.
[I 2025-06-10 11:07:16,989] Trial 35 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 86, 'max_depth': 13}. Best is trial 29 with value: 0.7821229050279329.
[I 2025-06-10 11:07:18,484] Trial 36 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 121, 'max_depth': 16}. Best is trial 29 with value: 0.7821229050279329.
[I 2025-06-10 11:07:20,787] Trial 37 finished with value: 0.7765363128491619 and parameters: {'n_estimators': 134, 'max_depth': 19}. Best is trial 29 with value: 0.7821229050279329.
[I 2025-06-10 11:07:21,854] Trial 38 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 92, 'max_depth': 17}. Best is trial 29 with value: 0.7821229050279329.
[I 2025-06-10 11:07:23,441] Trial 39 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 64, 'max_depth': 11}. Best is trial 29 with value: 0.7821229050279329.
[I 2025-06-10 11:07:25,077] Trial 40 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 79, 'max_depth': 15}. Best is trial 29 with value: 0.7821229050279329.
[I 2025-06-10 11:07:27,122] Trial 41 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 105, 'max_depth': 12}. Best is trial 29 with value: 0.7821229050279329.
[I 2025-06-10 11:07:29,249] Trial 42 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 94, 'max_depth': 12}. Best is trial 29 with value: 0.7821229050279329.
[I 2025-06-10 11:07:30,689] Trial 43 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 105, 'max_depth': 13}. Best is trial 29 with value: 0.7821229050279329.
[I 2025-06-10 11:07:32,104] Trial 44 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 119, 'max_depth': 7}. Best is trial 29 with value: 0.7821229050279329.
[I 2025-06-10 11:07:33,695] Trial 45 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 119, 'max_depth': 6}. Best is trial 29 with value: 0.7821229050279329.
[I 2025-06-10 11:07:35,680] Trial 46 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 128, 'max_depth': 3}. Best is trial 29 with value: 0.7821229050279329.
[I 2025-06-10 11:07:37,340] Trial 47 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 142, 'max_depth': 8}. Best is trial 29 with value: 0.7821229050279329.
[I 2025-06-10 11:07:38,518] Trial 48 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 106, 'max_depth': 8}. Best is trial 29 with value: 0.7821229050279329.
[I 2025-06-10 11:07:39,994] Trial 49 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 134, 'max_depth': 6}. Best is trial 29 with value: 0.7821229050279329.

In [8]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7821229050279329
Best hyperparameters: {'n_estimators': 107, 'max_depth': 15}

In [9]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.76

# Sampler in Optuna

In [10]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

# Define the objective function
def objective(trial):
    # Suggest values for the hyperparameters
    n_estimators = trial.suggest_int('n_estimators', 50, 200)
    max_depth = trial.suggest_int('max_depth', 3, 20)

    # Create the RandomForestClassifier with suggested hyperparameters
    model = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=max_depth,
        random_state=42
    )

    # Perform 3-fold cross-validation and calculate accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()

    return score  # Return the accuracy score for Optuna to maximize

In [11]:
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.RandomSampler())  # We aim to maximize accuracy
study.optimize(objective, n_trials=50)  # Run 50 trials to find the best hyperparameters

[I 2025-06-10 11:07:40,502] A new study created in memory with name: no-name-8ae86fbf-4417-437b-a129-f017caf927e8
[I 2025-06-10 11:07:42,433] Trial 0 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 138, 'max_depth': 9}. Best is trial 0 with value: 0.7635009310986964.
[I 2025-06-10 11:07:43,724] Trial 1 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 95, 'max_depth': 6}. Best is trial 0 with value: 0.7635009310986964.
[I 2025-06-10 11:07:44,848] Trial 2 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 111, 'max_depth': 17}. Best is trial 2 with value: 0.7746741154562384.
[I 2025-06-10 11:07:46,072] Trial 3 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 116, 'max_depth': 15}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:07:47,163] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:07:47,829] Trial 5 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 73, 'max_depth': 12}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:07:49,702] Trial 6 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 164, 'max_depth': 11}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:07:51,021] Trial 7 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 127, 'max_depth': 11}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:07:51,953] Trial 8 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 54, 'max_depth': 6}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:07:52,498] Trial 9 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 56, 'max_depth': 16}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:07:53,563] Trial 10 finished with value: 0.7560521415270017 and parameters: {'n_estimators': 58, 'max_depth': 4}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:07:55,669] Trial 11 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 183, 'max_depth': 15}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:07:57,476] Trial 12 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 197, 'max_depth': 8}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:07:58,363] Trial 13 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 95, 'max_depth': 5}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:08:00,496] Trial 14 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 173, 'max_depth': 8}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:08:01,895] Trial 15 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 53, 'max_depth': 10}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:08:04,264] Trial 16 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 136, 'max_depth': 15}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:08:04,907] Trial 17 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 68, 'max_depth': 9}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:08:05,954] Trial 18 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 99, 'max_depth': 20}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:08:07,044] Trial 19 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 98, 'max_depth': 18}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:08:07,858] Trial 20 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 66, 'max_depth': 3}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:08:08,622] Trial 21 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 76, 'max_depth': 16}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:08:09,926] Trial 22 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 117, 'max_depth': 18}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:08:10,744] Trial 23 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 68, 'max_depth': 3}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:08:13,462] Trial 24 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 178, 'max_depth': 17}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:08:16,181] Trial 25 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 147, 'max_depth': 13}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:08:17,178] Trial 26 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 108, 'max_depth': 6}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:08:17,824] Trial 27 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 19}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:08:19,885] Trial 28 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 118, 'max_depth': 5}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:08:21,654] Trial 29 finished with value: 0.756052141527002 and parameters: {'n_estimators': 93, 'max_depth': 3}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:08:22,658] Trial 30 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 63, 'max_depth': 18}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:08:23,734] Trial 31 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 85, 'max_depth': 6}. Best is trial 3 with value: 0.7765363128491621.
[I 2025-06-10 11:08:25,652] Trial 32 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 132, 'max_depth': 12}. Best is trial 32 with value: 0.7783985102420856.
[I 2025-06-10 11:08:28,258] Trial 33 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 152, 'max_depth': 3}. Best is trial 32 with value: 0.7783985102420856.
[I 2025-06-10 11:08:29,427] Trial 34 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 117, 'max_depth': 19}. Best is trial 32 with value: 0.7783985102420856.
[I 2025-06-10 11:08:31,158] Trial 35 finished with value: 0.7802607076350093 and parameters: {'n_estimators': 123, 'max_depth': 17}. Best is trial 35 with value: 0.7802607076350093.
[I 2025-06-10 11:08:32,266] Trial 36 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 81, 'max_depth': 19}. Best is trial 35 with value: 0.7802607076350093.
[I 2025-06-10 11:08:33,674] Trial 37 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 71, 'max_depth': 20}. Best is trial 35 with value: 0.7802607076350093.
[I 2025-06-10 11:08:34,796] Trial 38 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 88, 'max_depth': 4}. Best is trial 35 with value: 0.7802607076350093.
[I 2025-06-10 11:08:35,199] Trial 39 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 50, 'max_depth': 4}. Best is trial 35 with value: 0.7802607076350093.
[I 2025-06-10 11:08:36,086] Trial 40 finished with value: 0.7783985102420857 and parameters: {'n_estimators': 71, 'max_depth': 19}. Best is trial 35 with value: 0.7802607076350093.
[I 2025-06-10 11:08:37,419] Trial 41 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 148, 'max_depth': 14}. Best is trial 35 with value: 0.7802607076350093.
[I 2025-06-10 11:08:39,490] Trial 42 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 170, 'max_depth': 18}. Best is trial 35 with value: 0.7802607076350093.
[I 2025-06-10 11:08:40,939] Trial 43 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 95, 'max_depth': 3}. Best is trial 35 with value: 0.7802607076350093.
[I 2025-06-10 11:08:43,749] Trial 44 finished with value: 0.7765363128491621 and parameters: {'n_estimators': 188, 'max_depth': 19}. Best is trial 35 with value: 0.7802607076350093.
[I 2025-06-10 11:08:44,440] Trial 45 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 65, 'max_depth': 10}. Best is trial 35 with value: 0.7802607076350093.
[I 2025-06-10 11:08:45,917] Trial 46 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 153, 'max_depth': 10}. Best is trial 35 with value: 0.7802607076350093.
[I 2025-06-10 11:08:46,412] Trial 47 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 51, 'max_depth': 13}. Best is trial 35 with value: 0.7802607076350093.
[I 2025-06-10 11:08:47,244] Trial 48 finished with value: 0.756052141527002 and parameters: {'n_estimators': 91, 'max_depth': 3}. Best is trial 35 with value: 0.7802607076350093.
[I 2025-06-10 11:08:48,635] Trial 49 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 91, 'max_depth': 15}. Best is trial 35 with value: 0.7802607076350093.

In [12]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7802607076350093
Best hyperparameters: {'n_estimators': 123, 'max_depth': 17}

In [13]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

In [14]:
## Grid search

search_space = {
    'n_estimators': [50, 100, 150, 200],
    'max_depth': [5, 10, 15, 20]
}

In [15]:
# Create a study and optimize it using GridSampler
study = optuna.create_study(direction='maximize', sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2025-06-10 11:08:49,314] A new study created in memory with name: no-name-15c0fd49-e9a5-4b66-a8a0-801baf95d814
[I 2025-06-10 11:08:50,288] Trial 0 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7690875232774674.
[I 2025-06-10 11:08:51,873] Trial 1 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7690875232774674.
[I 2025-06-10 11:08:52,579] Trial 2 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-10 11:08:53,670] Trial 3 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-10 11:08:54,828] Trial 4 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-10 11:08:55,533] Trial 5 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-10 11:08:57,603] Trial 6 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-10 11:08:59,134] Trial 7 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-10 11:09:00,900] Trial 8 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-10 11:09:03,011] Trial 9 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-10 11:09:04,995] Trial 10 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-10 11:09:06,974] Trial 11 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-10 11:09:09,073] Trial 12 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 2 with value: 0.7728119180633147.
[I 2025-06-10 11:09:09,572] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 13 with value: 0.7746741154562384.
[I 2025-06-10 11:09:10,462] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 13 with value: 0.7746741154562384.
[I 2025-06-10 11:09:10,900] Trial 15 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 13 with value: 0.7746741154562384.

In [16]:

# Print the best result
print(f'Best trial accuracy: {study.best_trial.value}')
print(f'Best hyperparameters: {study.best_trial.params}')

Best trial accuracy: 0.7746741154562384
Best hyperparameters: {'n_estimators': 50, 'max_depth': 5}

In [17]:
from sklearn.metrics import accuracy_score

# Train a RandomForestClassifier using the best hyperparameters from Optuna
best_model = RandomForestClassifier(**study.best_trial.params, random_state=42)

# Fit the model to the training data
best_model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = best_model.predict(X_test)

# Calculate the accuracy on the test set
test_accuracy = accuracy_score(y_test, y_pred)

# Print the test accuracy
print(f'Test Accuracy with best hyperparameters: {test_accuracy:.2f}')

Test Accuracy with best hyperparameters: 0.74

# Optuna Vizulizations

In [18]:
# For visualizations
from optuna.visualization import plot_optimization_history, plot_parallel_coordinate, plot_slice, plot_contour, plot_param_importances

In [19]:
# 1. Optimization History
plot_optimization_history(study).show()

In [20]:
# 2. Parallel Coordinates Plot
plot_parallel_coordinate(study).show()

In [21]:
# 3. Slice Plot
plot_slice(study).show()

In [22]:
# 4. Contour Plot
plot_contour(study).show()

In [23]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

# Optimizing multiple model

In [24]:
# Importing the required libraries
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

In [25]:
# Define the objective function for Optuna
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [26]:
# Create a study and optimize it using CmaEsSampler
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100)

[I 2025-06-10 11:11:08,135] A new study created in memory with name: no-name-63117afa-2792-42e6-aee4-e4061f341642
[I 2025-06-10 11:11:11,764] Trial 0 finished with value: 0.7597765363128491 and parameters: {'classifier': 'RandomForest', 'n_estimators': 191, 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 0 with value: 0.7597765363128491.
[I 2025-06-10 11:11:15,704] Trial 1 finished with value: 0.7355679702048418 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 82, 'learning_rate': 0.09480523442065009, 'max_depth': 17, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 0 with value: 0.7597765363128491.
[I 2025-06-10 11:11:15,784] Trial 2 finished with value: 0.7243947858472999 and parameters: {'classifier': 'SVM', 'C': 1.3333157230142283, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 0 with value: 0.7597765363128491.
[I 2025-06-10 11:11:15,836] Trial 3 finished with value: 0.7299813780260708 and parameters: {'classifier': 'SVM', 'C': 0.9069652669005748, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 0 with value: 0.7597765363128491.
[I 2025-06-10 11:11:16,720] Trial 4 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 94, 'max_depth': 11, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 4 with value: 0.7635009310986964.
[I 2025-06-10 11:11:16,772] Trial 5 finished with value: 0.6983240223463687 and parameters: {'classifier': 'SVM', 'C': 27.72513027555906, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 4 with value: 0.7635009310986964.
[I 2025-06-10 11:11:18,710] Trial 6 finished with value: 0.7430167597765363 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 100, 'learning_rate': 0.07896292769760808, 'max_depth': 8, 'min_samples_split': 8, 'min_samples_leaf': 10}. Best is trial 4 with value: 0.7635009310986964.
[I 2025-06-10 11:11:18,780] Trial 7 finished with value: 0.7486033519553073 and parameters: {'classifier': 'SVM', 'C': 0.14682161275218625, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 4 with value: 0.7635009310986964.
[I 2025-06-10 11:11:19,900] Trial 8 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 98, 'max_depth': 19, 'min_samples_split': 4, 'min_samples_leaf': 3, 'bootstrap': False}. Best is trial 8 with value: 0.7653631284916201.
[I 2025-06-10 11:11:22,094] Trial 9 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 145, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 9 with value: 0.7728119180633147.
[I 2025-06-10 11:11:25,125] Trial 10 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 290, 'max_depth': 4, 'min_samples_split': 10, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 9 with value: 0.7728119180633147.
[I 2025-06-10 11:11:28,899] Trial 11 finished with value: 0.7467411545623835 and parameters: {'classifier': 'RandomForest', 'n_estimators': 300, 'max_depth': 3, 'min_samples_split': 10, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 9 with value: 0.7728119180633147.
[I 2025-06-10 11:11:31,883] Trial 12 finished with value: 0.7486033519553073 and parameters: {'classifier': 'RandomForest', 'n_estimators': 201, 'max_depth': 3, 'min_samples_split': 7, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 9 with value: 0.7728119180633147.
[I 2025-06-10 11:11:36,736] Trial 13 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 298, 'max_depth': 7, 'min_samples_split': 9, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 9 with value: 0.7728119180633147.
[I 2025-06-10 11:11:38,399] Trial 14 finished with value: 0.7765363128491619 and parameters: {'classifier': 'RandomForest', 'n_estimators': 151, 'max_depth': 8, 'min_samples_split': 6, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 14 with value: 0.7765363128491619.
[I 2025-06-10 11:11:40,943] Trial 15 finished with value: 0.7635009310986964 and parameters: {'classifier': 'RandomForest', 'n_estimators': 148, 'max_depth': 12, 'min_samples_split': 6, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 14 with value: 0.7765363128491619.
[I 2025-06-10 11:11:47,095] Trial 16 finished with value: 0.7430167597765364 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 147, 'learning_rate': 0.010616999706343302, 'max_depth': 11, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 14 with value: 0.7765363128491619.
[I 2025-06-10 11:11:49,584] Trial 17 finished with value: 0.7765363128491621 and parameters: {'classifier': 'RandomForest', 'n_estimators': 236, 'max_depth': 9, 'min_samples_split': 2, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 17 with value: 0.7765363128491621.
[I 2025-06-10 11:11:52,969] Trial 18 finished with value: 0.761638733705773 and parameters: {'classifier': 'RandomForest', 'n_estimators': 252, 'max_depth': 14, 'min_samples_split': 2, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 17 with value: 0.7765363128491621.
[I 2025-06-10 11:11:59,219] Trial 19 finished with value: 0.7541899441340782 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 218, 'learning_rate': 0.23615460448797232, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 4}. Best is trial 17 with value: 0.7765363128491621.
[I 2025-06-10 11:12:01,875] Trial 20 finished with value: 0.761638733705773 and parameters: {'classifier': 'RandomForest', 'n_estimators': 235, 'max_depth': 15, 'min_samples_split': 2, 'min_samples_leaf': 2, 'bootstrap': False}. Best is trial 17 with value: 0.7765363128491621.
[I 2025-06-10 11:12:03,425] Trial 21 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 152, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 17 with value: 0.7765363128491621.
[I 2025-06-10 11:12:04,694] Trial 22 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 129, 'max_depth': 5, 'min_samples_split': 5, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 17 with value: 0.7765363128491621.
[I 2025-06-10 11:12:06,784] Trial 23 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 171, 'max_depth': 9, 'min_samples_split': 3, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 17 with value: 0.7765363128491621.
[I 2025-06-10 11:12:07,881] Trial 24 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 61, 'max_depth': 10, 'min_samples_split': 7, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 17 with value: 0.7765363128491621.
[I 2025-06-10 11:12:09,283] Trial 25 finished with value: 0.7728119180633147 and parameters: {'classifier': 'RandomForest', 'n_estimators': 118, 'max_depth': 6, 'min_samples_split': 3, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 17 with value: 0.7765363128491621.
[I 2025-06-10 11:12:12,233] Trial 26 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 178, 'max_depth': 13, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 17 with value: 0.7765363128491621.
[I 2025-06-10 11:12:15,742] Trial 27 finished with value: 0.7765363128491621 and parameters: {'classifier': 'RandomForest', 'n_estimators': 258, 'max_depth': 8, 'min_samples_split': 7, 'min_samples_leaf': 5, 'bootstrap': False}. Best is trial 17 with value: 0.7765363128491621.
[I 2025-06-10 11:12:16,458] Trial 28 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 77.75418981821934, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:17,167] Trial 29 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 83.78092915547904, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:17,708] Trial 30 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 72.2240318640334, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:18,509] Trial 31 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 96.93152597021975, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:19,126] Trial 32 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 78.3932204385857, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:20,308] Trial 33 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 97.92860129542923, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:20,656] Trial 34 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 21.99540013716678, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:22,284] Trial 35 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 99.4603832382472, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:22,859] Trial 36 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 21.944182209266042, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:23,425] Trial 37 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 36.88615799915988, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:24,116] Trial 38 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 43.665893329252974, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:24,367] Trial 39 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 7.278994682676353, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:25,149] Trial 40 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 99.54674469427076, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:25,689] Trial 41 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 58.61466958412245, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:26,142] Trial 42 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 51.554511150037676, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:26,253] Trial 43 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 12.398992658817553, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:26,314] Trial 44 finished with value: 0.6890130353817505 and parameters: {'classifier': 'SVM', 'C': 97.74861404493348, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:26,438] Trial 45 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 49.65268815627539, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:26,963] Trial 46 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 54.381162663382604, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:27,147] Trial 47 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 14.016283922372821, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:29,836] Trial 48 finished with value: 0.7299813780260708 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 55, 'learning_rate': 0.012166432741989926, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 1}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:30,540] Trial 49 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 69.11033612981093, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:31,040] Trial 50 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 36.175260269318755, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:31,967] Trial 51 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 91.29151920853309, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:32,875] Trial 52 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 97.86280307752074, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:33,258] Trial 53 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 54.31186502690013, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:33,678] Trial 54 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 67.76089288799365, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:38,501] Trial 55 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 279, 'learning_rate': 0.026402616998012444, 'max_depth': 17, 'min_samples_split': 9, 'min_samples_leaf': 9}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:38,599] Trial 56 finished with value: 0.7355679702048418 and parameters: {'classifier': 'SVM', 'C': 31.01228689244586, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:38,812] Trial 57 finished with value: 0.6834264432029795 and parameters: {'classifier': 'SVM', 'C': 66.77713854543046, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:38,850] Trial 58 finished with value: 0.7188081936685289 and parameters: {'classifier': 'SVM', 'C': 2.409100601857872, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:38,941] Trial 59 finished with value: 0.7039106145251397 and parameters: {'classifier': 'SVM', 'C': 37.64673694961252, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:42,019] Trial 60 finished with value: 0.7318435754189944 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 199, 'learning_rate': 0.2690316007996542, 'max_depth': 16, 'min_samples_split': 9, 'min_samples_leaf': 9}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:42,157] Trial 61 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 17.99047296230452, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:42,576] Trial 62 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 69.50113766217262, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:42,674] Trial 63 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 8.498025586024625, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:42,869] Trial 64 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 23.326561633778518, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:42,915] Trial 65 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.43253510437589643, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:43,297] Trial 66 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 72.33919771899596, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:43,414] Trial 67 finished with value: 0.707635009310987 and parameters: {'classifier': 'SVM', 'C': 27.39848319724173, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:43,477] Trial 68 finished with value: 0.696461824953445 and parameters: {'classifier': 'SVM', 'C': 42.05799835416582, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:43,566] Trial 69 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 3.548616583318213, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:44,000] Trial 70 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 77.27785607789852, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:44,542] Trial 71 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 96.45049137626722, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:45,143] Trial 72 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 99.95195664741696, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:45,463] Trial 73 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 47.72845731640102, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:45,564] Trial 74 finished with value: 0.7150837988826816 and parameters: {'classifier': 'SVM', 'C': 68.17437470441779, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:45,799] Trial 75 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 43.597524196863006, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:50,206] Trial 76 finished with value: 0.7411545623836125 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 268, 'learning_rate': 0.03799281355756774, 'max_depth': 19, 'min_samples_split': 9, 'min_samples_leaf': 10}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:50,493] Trial 77 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 60.585151909700976, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:50,893] Trial 78 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 76.23282600595795, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.
[I 2025-06-10 11:12:51,145] Trial 79 finished with value: 0.7858472998137801 and parameters: {'classifier': 'SVM', 'C': 35.04326751608539, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 28 with value: 0.7858472998137801.

In [27]:
# Retrieve the best trial
best_trial = study.best_trial
print("Best trial parameters:", best_trial.params)
print("Best trial accuracy:", best_trial.value)

Best trial parameters: {'classifier': 'SVM', 'C': 0.12794321169134254, 'kernel': 'linear', 'gamma': 'auto'}
Best trial accuracy: 0.7895716945996275

In [28]:
study.trials_dataframe()

    number     value  ... params_n_estimators     state
0        0  0.759777  ...               191.0  COMPLETE
1        1  0.735568  ...                82.0  COMPLETE
2        2  0.724395  ...                 NaN  COMPLETE
3        3  0.729981  ...                 NaN  COMPLETE
4        4  0.763501  ...                94.0  COMPLETE
..     ...       ...  ...                 ...       ...
95      95  0.785847  ...                 NaN  COMPLETE
96      96  0.785847  ...                 NaN  COMPLETE
97      97  0.785847  ...                 NaN  COMPLETE
98      98  0.785847  ...                 NaN  COMPLETE
99      99  0.789572  ...                 NaN  COMPLETE

[100 rows x 16 columns]

In [29]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 71
RandomForest        20
GradientBoosting     9
Name: count, dtype: int64

In [30]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.740327
RandomForest        0.767039
SVM                 0.769691
Name: value, dtype: float64

In [31]:
# 1. Optimization History
plot_optimization_history(study).show()

In [32]:
# 3. Slice Plot
plot_slice(study).show()

In [33]:
# 5. Hyperparameter Importance
plot_param_importances(study).show()

In [36]:
import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np

# Load the Iris dataset
X, y = load_iris(return_X_y=True)

# Split the dataset into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define the objective function for XGBoost
def objective(trial):
    # Hyperparameter search space
    param = {
        'verbosity': 0,
        'objective': 'multi:softprob',
        'num_class': 3,
        'eval_metric': 'mlogloss',  # Ensure that the eval_metric is specified here
        'booster': 'gbtree',
        'lambda': trial.suggest_float('lambda', 1e-8, 1.0, log=True),
        'alpha': trial.suggest_float('alpha', 1e-8, 1.0, log=True),
        'eta': trial.suggest_float('eta', 0.01, 0.3),
        'gamma': trial.suggest_float('gamma', 1e-8, 1.0, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 9),
        'min_child_weight': trial.suggest_int('min_child_weight', 1, 10),
        'subsample': trial.suggest_float('subsample', 0.4, 1.0),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'n_estimators': 300,
    }

    # Create DMatrix for XGBoost
    dtrain = xgb.DMatrix(X_train, label=y_train)
    dtest = xgb.DMatrix(X_test, label=y_test)

    # Define a pruning callback based on evaluation metrics
    pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "eval-mlogloss")  # Match the metric name in the evals list

    # Train the model
    bst = xgb.train(
        param,
        dtrain,
        num_boost_round=300,
        evals=[(dtrain, "train"), (dtest, "eval")],  # Ensure the eval datasets and names are specified
        early_stopping_rounds=30,
        callbacks=[pruning_callback]
    )

    # Predict on the test set
    preds = bst.predict(dtest)
    best_preds = [int(np.argmax(line)) for line in preds]

    # Return accuracy as the objective value
    accuracy = accuracy_score(y_test, best_preds)
    return accuracy

# Create a study with pruning
study = optuna.create_study(direction='maximize', pruner=optuna.pruners.SuccessiveHalvingPruner())
study.optimize(objective, n_trials=50)

# Output the best trial
print(f"Best trial: {study.best_trial.params}")
print(f"Best accuracy: {study.best_value}")

[I 2025-06-10 11:13:35,582] A new study created in memory with name: no-name-249b5294-83dc-450b-b076-cba8535119fa

[0]	train-mlogloss:0.88018	eval-mlogloss:0.87211
[1]	train-mlogloss:0.79557	eval-mlogloss:0.77344
[2]	train-mlogloss:0.67049	eval-mlogloss:0.64056
[3]	train-mlogloss:0.56019	eval-mlogloss:0.51874
[4]	train-mlogloss:0.47511	eval-mlogloss:0.43120
[5]	train-mlogloss:0.40769	eval-mlogloss:0.36461
[6]	train-mlogloss:0.34896	eval-mlogloss:0.29890
[7]	train-mlogloss:0.30724	eval-mlogloss:0.25900
[8]	train-mlogloss:0.27603	eval-mlogloss:0.22307
[9]	train-mlogloss:0.24606	eval-mlogloss:0.19400
[10]	train-mlogloss:0.22281	eval-mlogloss:0.16589
[11]	train-mlogloss:0.20493	eval-mlogloss:0.14525
[12]	train-mlogloss:0.19594	eval-mlogloss:0.13811
[13]	train-mlogloss:0.18420	eval-mlogloss:0.12579
[14]	train-mlogloss:0.18300	eval-mlogloss:0.12585
[15]	train-mlogloss:0.17534	eval-mlogloss:0.11688
[16]	train-mlogloss:0.17335	eval-mlogloss:0.11420
[17]	train-mlogloss:0.16857	eval-mlogloss:0.10717
[18]	train-mlogloss:0.16783	eval-mlogloss:0.10914
[19]	train-mlogloss:0.16225	eval-mlogloss:0.10307
[20]	train-mlogloss:0.16076	eval-mlogloss:0.10143
[21]	train-mlogloss:0.16017	eval-mlogloss:0.10073
[22]	train-mlogloss:0.16026	eval-mlogloss:0.09746
[23]	train-mlogloss:0.15607	eval-mlogloss:0.09224
[24]	train-mlogloss:0.15582	eval-mlogloss:0.09141
[25]	train-mlogloss:0.15215	eval-mlogloss:0.08616
[26]	train-mlogloss:0.15099	eval-mlogloss:0.08510
[27]	train-mlogloss:0.15137	eval-mlogloss:0.08681
[28]	train-mlogloss:0.15057	eval-mlogloss:0.08564
[29]	train-mlogloss:0.14953	eval-mlogloss:0.08505
[30]	train-mlogloss:0.14943	eval-mlogloss:0.08592
[31]	train-mlogloss:0.14929	eval-mlogloss:0.08610
[32]	train-mlogloss:0.14943	eval-mlogloss:0.08657
[33]	train-mlogloss:0.14466	eval-mlogloss:0.08046
[34]	train-mlogloss:0.14424	eval-mlogloss:0.08033
[35]	train-mlogloss:0.14413	eval-mlogloss:0.08031
[36]	train-mlogloss:0.14430	eval-mlogloss:0.08054
[37]	train-mlogloss:0.14527	eval-mlogloss:0.08282
[38]	train-mlogloss:0.14510	eval-mlogloss:0.08281
[39]	train-mlogloss:0.14442	eval-mlogloss:0.08238
[40]	train-mlogloss:0.14388	eval-mlogloss:0.08316
[41]	train-mlogloss:0.14315	eval-mlogloss:0.08273
[42]	train-mlogloss:0.14322	eval-mlogloss:0.08271
[43]	train-mlogloss:0.14394	eval-mlogloss:0.08354
[44]	train-mlogloss:0.14374	eval-mlogloss:0.08332
[45]	train-mlogloss:0.14286	eval-mlogloss:0.08257
[46]	train-mlogloss:0.14163	eval-mlogloss:0.07960
[47]	train-mlogloss:0.14181	eval-mlogloss:0.08027
[48]	train-mlogloss:0.14206	eval-mlogloss:0.07964
[49]	train-mlogloss:0.14105	eval-mlogloss:0.07777
[50]	train-mlogloss:0.13833	eval-mlogloss:0.07288
[51]	train-mlogloss:0.13794	eval-mlogloss:0.07045
[52]	train-mlogloss:0.13837	eval-mlogloss:0.07095
[53]	train-mlogloss:0.13786	eval-mlogloss:0.07009
[54]	train-mlogloss:0.13709	eval-mlogloss:0.06895
[55]	train-mlogloss:0.13684	eval-mlogloss:0.06820
[56]	train-mlogloss:0.13665	eval-mlogloss:0.06809
[57]	train-mlogloss:0.13666	eval-mlogloss:0.06798
[58]	train-mlogloss:0.13708	eval-mlogloss:0.06830
[59]	train-mlogloss:0.13679	eval-mlogloss:0.06865
[60]	train-mlogloss:0.13642	eval-mlogloss:0.06842
[61]	train-mlogloss:0.13609	eval-mlogloss:0.06834
[62]	train-mlogloss:0.13557	eval-mlogloss:0.06831
[63]	train-mlogloss:0.13515	eval-mlogloss:0.06856
[64]	train-mlogloss:0.13511	eval-mlogloss:0.06858
[65]	train-mlogloss:0.13555	eval-mlogloss:0.06890
[66]	train-mlogloss:0.13478	eval-mlogloss:0.06775
[67]	train-mlogloss:0.13445	eval-mlogloss:0.06764
[68]	train-mlogloss:0.13447	eval-mlogloss:0.06759
[69]	train-mlogloss:0.13404	eval-mlogloss:0.06676
[70]	train-mlogloss:0.13402	eval-mlogloss:0.06672
[71]	train-mlogloss:0.13406	eval-mlogloss:0.06672
[72]	train-mlogloss:0.13407	eval-mlogloss:0.06655
[73]	train-mlogloss:0.13401	eval-mlogloss:0.06628
[74]	train-mlogloss:0.13405	eval-mlogloss:0.06624
[75]	train-mlogloss:0.13410	eval-mlogloss:0.06653
[76]	train-mlogloss:0.13425	eval-mlogloss:0.06657
[77]	train-mlogloss:0.13423	eval-mlogloss:0.06658
[78]	train-mlogloss:0.13408	eval-mlogloss:0.06713
[79]	train-mlogloss:0.13408	eval-mlogloss:0.06728
[80]	train-mlogloss:0.13406	eval-mlogloss:0.06739
[81]	train-mlogloss:0.13420	eval-mlogloss:0.06766
[82]	train-mlogloss:0.13443	eval-mlogloss:0.06877
[83]	train-mlogloss:0.13451	eval-mlogloss:0.06881
[84]	train-mlogloss:0.13265	eval-mlogloss:0.06660
[85]	train-mlogloss:0.13267	eval-mlogloss:0.06677
[86]	train-mlogloss:0.13260	eval-mlogloss:0.06788
[87]	train-mlogloss:0.13236	eval-mlogloss:0.06774
[88]	train-mlogloss:0.13183	eval-mlogloss:0.06701
[89]	train-mlogloss:0.13187	eval-mlogloss:0.06680
[90]	train-mlogloss:0.13158	eval-mlogloss:0.06597
[91]	train-mlogloss:0.13176	eval-mlogloss:0.06636
[92]	train-mlogloss:0.13157	eval-mlogloss:0.06626
[93]	train-mlogloss:0.13137	eval-mlogloss:0.06588
[94]	train-mlogloss:0.13084	eval-mlogloss:0.06530
[95]	train-mlogloss:0.13116	eval-mlogloss:0.06586
[96]	train-mlogloss:0.13134	eval-mlogloss:0.06587
[97]	train-mlogloss:0.13122	eval-mlogloss:0.06567
[98]	train-mlogloss:0.13153	eval-mlogloss:0.06588
[99]	train-mlogloss:0.12970	eval-mlogloss:0.06640
[100]	train-mlogloss:0.12926	eval-mlogloss:0.06579
[101]	train-mlogloss:0.12899	eval-mlogloss:0.06529
[102]	train-mlogloss:0.12912	eval-mlogloss:0.06549
[103]	train-mlogloss:0.12870	eval-mlogloss:0.06519
[104]	train-mlogloss:0.12914	eval-mlogloss:0.06579
[105]	train-mlogloss:0.12881	eval-mlogloss:0.06534
[106]	train-mlogloss:0.12869	eval-mlogloss:0.06513
[107]	train-mlogloss:0.12932	eval-mlogloss:0.06619
[108]	train-mlogloss:0.12894	eval-mlogloss:0.06567
[109]	train-mlogloss:0.12864	eval-mlogloss:0.06487
[110]	train-mlogloss:0.12890	eval-mlogloss:0.06530
[111]	train-mlogloss:0.12846	eval-mlogloss:0.06477
[112]	train-mlogloss:0.12819	eval-mlogloss:0.06452
[113]	train-mlogloss:0.12820	eval-mlogloss:0.06435
[114]	train-mlogloss:0.12812	eval-mlogloss:0.06289
[115]	train-mlogloss:0.12806	eval-mlogloss:0.06301
[116]	train-mlogloss:0.12813	eval-mlogloss:0.06318
[117]	train-mlogloss:0.12797	eval-mlogloss:0.06269
[118]	train-mlogloss:0.12793	eval-mlogloss:0.06269
[119]	train-mlogloss:0.12801	eval-mlogloss:0.06267
[120]	train-mlogloss:0.12802	eval-mlogloss:0.06259
[121]	train-mlogloss:0.12796	eval-mlogloss:0.06257
[122]	train-mlogloss:0.12774	eval-mlogloss:0.06250
[123]	train-mlogloss:0.12717	eval-mlogloss:0.06153
[124]	train-mlogloss:0.12661	eval-mlogloss:0.06081
[125]	train-mlogloss:0.12664	eval-mlogloss:0.06068
[126]	train-mlogloss:0.12658	eval-mlogloss:0.06067
[127]	train-mlogloss:0.12679	eval-mlogloss:0.06079
[128]	train-mlogloss:0.12710	eval-mlogloss:0.06168
[129]	train-mlogloss:0.12718	eval-mlogloss:0.06182
[130]	train-mlogloss:0.12755	eval-mlogloss:0.06218
[131]	train-mlogloss:0.12847	eval-mlogloss:0.06317
[132]	train-mlogloss:0.12702	eval-mlogloss:0.06173
[133]	train-mlogloss:0.12663	eval-mlogloss:0.06150
[134]	train-mlogloss:0.12676	eval-mlogloss:0.06164
[135]	train-mlogloss:0.12695	eval-mlogloss:0.06179
[136]	train-mlogloss:0.12684	eval-mlogloss:0.06169
[137]	train-mlogloss:0.12664	eval-mlogloss:0.06154
[138]	train-mlogloss:0.12644	eval-mlogloss:0.06111
[139]	train-mlogloss:0.12651	eval-mlogloss:0.06105
[140]	train-mlogloss:0.12624	eval-mlogloss:0.06070
[141]	train-mlogloss:0.12638	eval-mlogloss:0.06066
[142]	train-mlogloss:0.12654	eval-mlogloss:0.06109
[143]	train-mlogloss:0.12657	eval-mlogloss:0.06131
[144]	train-mlogloss:0.12609	eval-mlogloss:0.06099
[145]	train-mlogloss:0.12642	eval-mlogloss:0.06133
[146]	train-mlogloss:0.12622	eval-mlogloss:0.06092
[147]	train-mlogloss:0.12591	eval-mlogloss:0.06090
[148]	train-mlogloss:0.12595	eval-mlogloss:0.06114
[149]	train-mlogloss:0.12582	eval-mlogloss:0.06112
[150]	train-mlogloss:0.12537	eval-mlogloss:0.06089
[151]	train-mlogloss:0.12536	eval-mlogloss:0.06094
[152]	train-mlogloss:0.12536	eval-mlogloss:0.06096
[153]	train-mlogloss:0.12395	eval-mlogloss:0.05948
[154]	train-mlogloss:0.12360	eval-mlogloss:0.05819
[155]	train-mlogloss:0.12395	eval-mlogloss:0.05765
[156]	train-mlogloss:0.12364	eval-mlogloss:0.05725
[157]	train-mlogloss:0.12359	eval-mlogloss:0.05726
[158]	train-mlogloss:0.12344	eval-mlogloss:0.05728
[159]	train-mlogloss:0.12292	eval-mlogloss:0.05710
[160]	train-mlogloss:0.12294	eval-mlogloss:0.05713
[161]	train-mlogloss:0.12287	eval-mlogloss:0.05722
[162]	train-mlogloss:0.12292	eval-mlogloss:0.05741
[163]	train-mlogloss:0.12305	eval-mlogloss:0.05754
[164]	train-mlogloss:0.12296	eval-mlogloss:0.05748
[165]	train-mlogloss:0.12311	eval-mlogloss:0.05745
[166]	train-mlogloss:0.12290	eval-mlogloss:0.05708
[167]	train-mlogloss:0.12269	eval-mlogloss:0.05674
[168]	train-mlogloss:0.12117	eval-mlogloss:0.05797
[169]	train-mlogloss:0.12124	eval-mlogloss:0.05783
[170]	train-mlogloss:0.12117	eval-mlogloss:0.05797
[171]	train-mlogloss:0.12127	eval-mlogloss:0.05817
[172]	train-mlogloss:0.12126	eval-mlogloss:0.05899
[173]	train-mlogloss:0.12128	eval-mlogloss:0.05896
[174]	train-mlogloss:0.12137	eval-mlogloss:0.05920
[175]	train-mlogloss:0.12136	eval-mlogloss:0.05898
[176]	train-mlogloss:0.12129	eval-mlogloss:0.05894
[177]	train-mlogloss:0.12135	eval-mlogloss:0.05963
[178]	train-mlogloss:0.12112	eval-mlogloss:0.05865
[179]	train-mlogloss:0.12134	eval-mlogloss:0.05866
[180]	train-mlogloss:0.12164	eval-mlogloss:0.05865
[181]	train-mlogloss:0.12138	eval-mlogloss:0.05861
[182]	train-mlogloss:0.12124	eval-mlogloss:0.05819
[183]	train-mlogloss:0.12078	eval-mlogloss:0.05812
[184]	train-mlogloss:0.12074	eval-mlogloss:0.05801
[185]	train-mlogloss:0.12088	eval-mlogloss:0.05830
[186]	train-mlogloss:0.12096	eval-mlogloss:0.05801
[187]	train-mlogloss:0.12097	eval-mlogloss:0.05790
[188]	train-mlogloss:0.12097	eval-mlogloss:0.05803
[189]	train-mlogloss:0.12111	eval-mlogloss:0.05840
[190]	train-mlogloss:0.12105	eval-mlogloss:0.05845
[191]	train-mlogloss:0.12100	eval-mlogloss:0.05839
[192]	train-mlogloss:0.12087	eval-mlogloss:0.05833
[193]	train-mlogloss:0.12074	eval-mlogloss:0.05824
[194]	train-mlogloss:0.12052	eval-mlogloss:0.05833
[195]	train-mlogloss:0.12054	eval-mlogloss:0.05815
[196]	train-mlogloss:0.12057	eval-mlogloss:0.05798

[I 2025-06-10 11:13:36,613] Trial 0 finished with value: 1.0 and parameters: {'lambda': 0.00013695093332539675, 'alpha': 0.0008298234829026117, 'eta': 0.1824635846276565, 'gamma': 0.0006890317133960559, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.4219159808455654, 'colsample_bytree': 0.56114666874105}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.77069	eval-mlogloss:0.75920
[1]	train-mlogloss:0.57657	eval-mlogloss:0.55198
[2]	train-mlogloss:0.44118	eval-mlogloss:0.40944
[3]	train-mlogloss:0.34797	eval-mlogloss:0.31039
[4]	train-mlogloss:0.28251	eval-mlogloss:0.23795
[5]	train-mlogloss:0.23371	eval-mlogloss:0.18347
[6]	train-mlogloss:0.20098	eval-mlogloss:0.14540
[7]	train-mlogloss:0.17095	eval-mlogloss:0.11566
[8]	train-mlogloss:0.14930	eval-mlogloss:0.09748
[9]	train-mlogloss:0.13029	eval-mlogloss:0.08626
[10]	train-mlogloss:0.11618	eval-mlogloss:0.07356
[11]	train-mlogloss:0.11030	eval-mlogloss:0.06852
[12]	train-mlogloss:0.10519	eval-mlogloss:0.06406
[13]	train-mlogloss:0.10259	eval-mlogloss:0.06111
[14]	train-mlogloss:0.10175	eval-mlogloss:0.06230
[15]	train-mlogloss:0.10172	eval-mlogloss:0.06228
[16]	train-mlogloss:0.10024	eval-mlogloss:0.05922
[17]	train-mlogloss:0.09694	eval-mlogloss:0.05916
[18]	train-mlogloss:0.09623	eval-mlogloss:0.05712
[19]	train-mlogloss:0.09492	eval-mlogloss:0.05567
[20]	train-mlogloss:0.09494	eval-mlogloss:0.05567
[21]	train-mlogloss:0.09330	eval-mlogloss:0.05175
[22]	train-mlogloss:0.09328	eval-mlogloss:0.05174
[23]	train-mlogloss:0.09234	eval-mlogloss:0.05069
[24]	train-mlogloss:0.09233	eval-mlogloss:0.05067
[25]	train-mlogloss:0.09234	eval-mlogloss:0.05069
[26]	train-mlogloss:0.09167	eval-mlogloss:0.05035
[27]	train-mlogloss:0.09166	eval-mlogloss:0.05035
[28]	train-mlogloss:0.09167	eval-mlogloss:0.05035
[29]	train-mlogloss:0.09166	eval-mlogloss:0.05034
[30]	train-mlogloss:0.09164	eval-mlogloss:0.05033
[31]	train-mlogloss:0.09166	eval-mlogloss:0.05037
[32]	train-mlogloss:0.09163	eval-mlogloss:0.05035
[33]	train-mlogloss:0.09093	eval-mlogloss:0.04836
[34]	train-mlogloss:0.09091	eval-mlogloss:0.04834
[35]	train-mlogloss:0.09090	eval-mlogloss:0.04834
[36]	train-mlogloss:0.09008	eval-mlogloss:0.04955
[37]	train-mlogloss:0.09008	eval-mlogloss:0.04955
[38]	train-mlogloss:0.09009	eval-mlogloss:0.04954
[39]	train-mlogloss:0.09009	eval-mlogloss:0.04954
[40]	train-mlogloss:0.09009	eval-mlogloss:0.04954
[41]	train-mlogloss:0.09009	eval-mlogloss:0.04954
[42]	train-mlogloss:0.09009	eval-mlogloss:0.04955
[43]	train-mlogloss:0.09009	eval-mlogloss:0.04956
[44]	train-mlogloss:0.08914	eval-mlogloss:0.04701
[45]	train-mlogloss:0.08913	eval-mlogloss:0.04699
[46]	train-mlogloss:0.08916	eval-mlogloss:0.04698
[47]	train-mlogloss:0.08916	eval-mlogloss:0.04698
[48]	train-mlogloss:0.08914	eval-mlogloss:0.04698
[49]	train-mlogloss:0.08845	eval-mlogloss:0.04623
[50]	train-mlogloss:0.08845	eval-mlogloss:0.04622
[51]	train-mlogloss:0.08845	eval-mlogloss:0.04622
[52]	train-mlogloss:0.08844	eval-mlogloss:0.04626
[53]	train-mlogloss:0.08846	eval-mlogloss:0.04630
[54]	train-mlogloss:0.08846	eval-mlogloss:0.04626
[55]	train-mlogloss:0.08846	eval-mlogloss:0.04626
[56]	train-mlogloss:0.08845	eval-mlogloss:0.04626
[57]	train-mlogloss:0.08846	eval-mlogloss:0.04623
[58]	train-mlogloss:0.08849	eval-mlogloss:0.04622
[59]	train-mlogloss:0.08846	eval-mlogloss:0.04624
[60]	train-mlogloss:0.08842	eval-mlogloss:0.04623
[61]	train-mlogloss:0.08797	eval-mlogloss:0.04546
[62]	train-mlogloss:0.08797	eval-mlogloss:0.04548
[63]	train-mlogloss:0.08798	eval-mlogloss:0.04550
[64]	train-mlogloss:0.08798	eval-mlogloss:0.04550
[65]	train-mlogloss:0.08798	eval-mlogloss:0.04551
[66]	train-mlogloss:0.08716	eval-mlogloss:0.04697
[67]	train-mlogloss:0.08643	eval-mlogloss:0.04667
[68]	train-mlogloss:0.08640	eval-mlogloss:0.04665
[69]	train-mlogloss:0.08639	eval-mlogloss:0.04663
[70]	train-mlogloss:0.08639	eval-mlogloss:0.04663
[71]	train-mlogloss:0.08644	eval-mlogloss:0.04669
[72]	train-mlogloss:0.08639	eval-mlogloss:0.04656
[73]	train-mlogloss:0.08639	eval-mlogloss:0.04656
[74]	train-mlogloss:0.08640	eval-mlogloss:0.04652
[75]	train-mlogloss:0.08640	eval-mlogloss:0.04654
[76]	train-mlogloss:0.08647	eval-mlogloss:0.04666
[77]	train-mlogloss:0.08645	eval-mlogloss:0.04664
[78]	train-mlogloss:0.08648	eval-mlogloss:0.04672
[79]	train-mlogloss:0.08644	eval-mlogloss:0.04665
[80]	train-mlogloss:0.08643	eval-mlogloss:0.04664
[81]	train-mlogloss:0.08642	eval-mlogloss:0.04666
[82]	train-mlogloss:0.08641	eval-mlogloss:0.04665
[83]	train-mlogloss:0.08642	eval-mlogloss:0.04668
[84]	train-mlogloss:0.08641	eval-mlogloss:0.04666
[85]	train-mlogloss:0.08641	eval-mlogloss:0.04666
[86]	train-mlogloss:0.08641	eval-mlogloss:0.04666
[87]	train-mlogloss:0.08643	eval-mlogloss:0.04668
[88]	train-mlogloss:0.08564	eval-mlogloss:0.04432
[89]	train-mlogloss:0.08563	eval-mlogloss:0.04431
[90]	train-mlogloss:0.08559	eval-mlogloss:0.04426
[91]	train-mlogloss:0.08560	eval-mlogloss:0.04431
[92]	train-mlogloss:0.08560	eval-mlogloss:0.04430
[93]	train-mlogloss:0.08553	eval-mlogloss:0.04291
[94]	train-mlogloss:0.08553	eval-mlogloss:0.04292
[95]	train-mlogloss:0.08552	eval-mlogloss:0.04295
[96]	train-mlogloss:0.08553	eval-mlogloss:0.04289
[97]	train-mlogloss:0.08553	eval-mlogloss:0.04290
[98]	train-mlogloss:0.08556	eval-mlogloss:0.04297
[99]	train-mlogloss:0.08556	eval-mlogloss:0.04293
[100]	train-mlogloss:0.08557	eval-mlogloss:0.04290
[101]	train-mlogloss:0.08556	eval-mlogloss:0.04293
[102]	train-mlogloss:0.08556	eval-mlogloss:0.04295
[103]	train-mlogloss:0.08556	eval-mlogloss:0.04291
[104]	train-mlogloss:0.08554	eval-mlogloss:0.04293
[105]	train-mlogloss:0.08554	eval-mlogloss:0.04289
[106]	train-mlogloss:0.08554	eval-mlogloss:0.04289
[107]	train-mlogloss:0.08484	eval-mlogloss:0.04282
[108]	train-mlogloss:0.08488	eval-mlogloss:0.04284
[109]	train-mlogloss:0.08484	eval-mlogloss:0.04279
[110]	train-mlogloss:0.08486	eval-mlogloss:0.04287
[111]	train-mlogloss:0.08487	eval-mlogloss:0.04289
[112]	train-mlogloss:0.08486	eval-mlogloss:0.04287
[113]	train-mlogloss:0.08488	eval-mlogloss:0.04295
[114]	train-mlogloss:0.08487	eval-mlogloss:0.04293
[115]	train-mlogloss:0.08488	eval-mlogloss:0.04294
[116]	train-mlogloss:0.08483	eval-mlogloss:0.04287
[117]	train-mlogloss:0.08482	eval-mlogloss:0.04278
[118]	train-mlogloss:0.08482	eval-mlogloss:0.04276
[119]	train-mlogloss:0.08482	eval-mlogloss:0.04276
[120]	train-mlogloss:0.08482	eval-mlogloss:0.04279
[121]	train-mlogloss:0.08483	eval-mlogloss:0.04275
[122]	train-mlogloss:0.08484	eval-mlogloss:0.04283
[123]	train-mlogloss:0.08486	eval-mlogloss:0.04291
[124]	train-mlogloss:0.08485	eval-mlogloss:0.04289
[125]	train-mlogloss:0.08487	eval-mlogloss:0.04297
[126]	train-mlogloss:0.08486	eval-mlogloss:0.04295
[127]	train-mlogloss:0.08486	eval-mlogloss:0.04294
[128]	train-mlogloss:0.08483	eval-mlogloss:0.04290
[129]	train-mlogloss:0.08483	eval-mlogloss:0.04290
[130]	train-mlogloss:0.08490	eval-mlogloss:0.04301
[131]	train-mlogloss:0.08487	eval-mlogloss:0.04300
[132]	train-mlogloss:0.08483	eval-mlogloss:0.04291
[133]	train-mlogloss:0.08482	eval-mlogloss:0.04287
[134]	train-mlogloss:0.08485	eval-mlogloss:0.04300
[135]	train-mlogloss:0.08485	eval-mlogloss:0.04297
[136]	train-mlogloss:0.08485	eval-mlogloss:0.04298
[137]	train-mlogloss:0.08484	eval-mlogloss:0.04296
[138]	train-mlogloss:0.08484	eval-mlogloss:0.04296
[139]	train-mlogloss:0.08487	eval-mlogloss:0.04299
[140]	train-mlogloss:0.08429	eval-mlogloss:0.04098
[141]	train-mlogloss:0.08433	eval-mlogloss:0.04103
[142]	train-mlogloss:0.08436	eval-mlogloss:0.04108
[143]	train-mlogloss:0.08430	eval-mlogloss:0.04095
[144]	train-mlogloss:0.08432	eval-mlogloss:0.04101
[145]	train-mlogloss:0.08432	eval-mlogloss:0.04101
[146]	train-mlogloss:0.08429	eval-mlogloss:0.04092
[147]	train-mlogloss:0.08427	eval-mlogloss:0.04083
[148]	train-mlogloss:0.08427	eval-mlogloss:0.04083
[149]	train-mlogloss:0.08427	eval-mlogloss:0.04089
[150]	train-mlogloss:0.08427	eval-mlogloss:0.04082
[151]	train-mlogloss:0.08432	eval-mlogloss:0.03882
[152]	train-mlogloss:0.08430	eval-mlogloss:0.03887
[153]	train-mlogloss:0.08431	eval-mlogloss:0.03891
[154]	train-mlogloss:0.08430	eval-mlogloss:0.03884
[155]	train-mlogloss:0.08431	eval-mlogloss:0.03883
[156]	train-mlogloss:0.08431	eval-mlogloss:0.03883
[157]	train-mlogloss:0.08433	eval-mlogloss:0.03882
[158]	train-mlogloss:0.08429	eval-mlogloss:0.03886
[159]	train-mlogloss:0.08427	eval-mlogloss:0.03890
[160]	train-mlogloss:0.08427	eval-mlogloss:0.03890
[161]	train-mlogloss:0.08429	eval-mlogloss:0.03894
[162]	train-mlogloss:0.08429	eval-mlogloss:0.03893
[163]	train-mlogloss:0.08429	eval-mlogloss:0.03893
[164]	train-mlogloss:0.08433	eval-mlogloss:0.03898
[165]	train-mlogloss:0.08431	eval-mlogloss:0.03891
[166]	train-mlogloss:0.08431	eval-mlogloss:0.03891
[167]	train-mlogloss:0.08431	eval-mlogloss:0.03886
[168]	train-mlogloss:0.08431	eval-mlogloss:0.03885
[169]	train-mlogloss:0.08433	eval-mlogloss:0.03883
[170]	train-mlogloss:0.08433	eval-mlogloss:0.03882
[171]	train-mlogloss:0.08434	eval-mlogloss:0.03881
[172]	train-mlogloss:0.08434	eval-mlogloss:0.03880
[173]	train-mlogloss:0.08434	eval-mlogloss:0.03881
[174]	train-mlogloss:0.08433	eval-mlogloss:0.03881
[175]	train-mlogloss:0.08431	eval-mlogloss:0.03883
[176]	train-mlogloss:0.08431	eval-mlogloss:0.03883
[177]	train-mlogloss:0.08431	eval-mlogloss:0.03884
[178]	train-mlogloss:0.08430	eval-mlogloss:0.03884
[179]	train-mlogloss:0.08432	eval-mlogloss:0.03887
[180]	train-mlogloss:0.08432	eval-mlogloss:0.03886
[181]	train-mlogloss:0.08436	eval-mlogloss:0.03881
[182]	train-mlogloss:0.08437	eval-mlogloss:0.03881
[183]	train-mlogloss:0.08432	eval-mlogloss:0.03882
[184]	train-mlogloss:0.08432	eval-mlogloss:0.03882
[185]	train-mlogloss:0.08432	eval-mlogloss:0.03882
[186]	train-mlogloss:0.08432	eval-mlogloss:0.03882
[187]	train-mlogloss:0.08431	eval-mlogloss:0.03883
[188]	train-mlogloss:0.08431	eval-mlogloss:0.03883
[189]	train-mlogloss:0.08433	eval-mlogloss:0.03882
[190]	train-mlogloss:0.08431	eval-mlogloss:0.03884
[191]	train-mlogloss:0.08429	eval-mlogloss:0.03887
[192]	train-mlogloss:0.08429	eval-mlogloss:0.03886
[193]	train-mlogloss:0.08428	eval-mlogloss:0.03888
[194]	train-mlogloss:0.08427	eval-mlogloss:0.03890
[195]	train-mlogloss:0.08427	eval-mlogloss:0.03891
[196]	train-mlogloss:0.08427	eval-mlogloss:0.03892
[197]	train-mlogloss:0.08427	eval-mlogloss:0.03893
[198]	train-mlogloss:0.08427	eval-mlogloss:0.03893
[199]	train-mlogloss:0.08427	eval-mlogloss:0.03889
[200]	train-mlogloss:0.08428	eval-mlogloss:0.03886
[201]	train-mlogloss:0.08435	eval-mlogloss:0.03884
[202]	train-mlogloss:0.08434	eval-mlogloss:0.03884

[I 2025-06-10 11:13:39,096] Trial 1 finished with value: 1.0 and parameters: {'lambda': 0.001062152070410872, 'alpha': 0.16013739547671027, 'eta': 0.27700056276112417, 'gamma': 0.3799195409952126, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.902606582072063, 'colsample_bytree': 0.9665681373104906}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.75515	eval-mlogloss:0.74464

[I 2025-06-10 11:13:39,114] Trial 2 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.82034	eval-mlogloss:0.82330
[1]	train-mlogloss:0.69116	eval-mlogloss:0.71935
[2]	train-mlogloss:0.55021	eval-mlogloss:0.57072
[3]	train-mlogloss:0.43744	eval-mlogloss:0.44564
[4]	train-mlogloss:0.35604	eval-mlogloss:0.35835
[5]	train-mlogloss:0.29429	eval-mlogloss:0.29121
[6]	train-mlogloss:0.24480	eval-mlogloss:0.23555
[7]	train-mlogloss:0.20478	eval-mlogloss:0.18977
[8]	train-mlogloss:0.17397	eval-mlogloss:0.15940
[9]	train-mlogloss:0.14946	eval-mlogloss:0.13632
[10]	train-mlogloss:0.13153	eval-mlogloss:0.11835
[11]	train-mlogloss:0.11429	eval-mlogloss:0.10548
[12]	train-mlogloss:0.10390	eval-mlogloss:0.09187
[13]	train-mlogloss:0.09396	eval-mlogloss:0.08048
[14]	train-mlogloss:0.08613	eval-mlogloss:0.06959
[15]	train-mlogloss:0.08113	eval-mlogloss:0.06371
[16]	train-mlogloss:0.07635	eval-mlogloss:0.05943
[17]	train-mlogloss:0.07217	eval-mlogloss:0.05419
[18]	train-mlogloss:0.07083	eval-mlogloss:0.05272
[19]	train-mlogloss:0.06778	eval-mlogloss:0.05055
[20]	train-mlogloss:0.06646	eval-mlogloss:0.05028
[21]	train-mlogloss:0.06519	eval-mlogloss:0.04828
[22]	train-mlogloss:0.06340	eval-mlogloss:0.04529
[23]	train-mlogloss:0.06221	eval-mlogloss:0.04375
[24]	train-mlogloss:0.06117	eval-mlogloss:0.04252
[25]	train-mlogloss:0.06049	eval-mlogloss:0.04081
[26]	train-mlogloss:0.05915	eval-mlogloss:0.03904
[27]	train-mlogloss:0.05822	eval-mlogloss:0.03857
[28]	train-mlogloss:0.05757	eval-mlogloss:0.03756
[29]	train-mlogloss:0.05695	eval-mlogloss:0.03731
[30]	train-mlogloss:0.05655	eval-mlogloss:0.03772
[31]	train-mlogloss:0.05595	eval-mlogloss:0.03689
[32]	train-mlogloss:0.05516	eval-mlogloss:0.03690
[33]	train-mlogloss:0.05454	eval-mlogloss:0.03508
[34]	train-mlogloss:0.05398	eval-mlogloss:0.03494
[35]	train-mlogloss:0.05285	eval-mlogloss:0.03345
[36]	train-mlogloss:0.05224	eval-mlogloss:0.03291
[37]	train-mlogloss:0.05197	eval-mlogloss:0.03299
[38]	train-mlogloss:0.05148	eval-mlogloss:0.03286
[39]	train-mlogloss:0.05098	eval-mlogloss:0.03323
[40]	train-mlogloss:0.05073	eval-mlogloss:0.03324
[41]	train-mlogloss:0.05037	eval-mlogloss:0.03242
[42]	train-mlogloss:0.04994	eval-mlogloss:0.03149
[43]	train-mlogloss:0.04971	eval-mlogloss:0.03146
[44]	train-mlogloss:0.04926	eval-mlogloss:0.02969
[45]	train-mlogloss:0.04892	eval-mlogloss:0.03029
[46]	train-mlogloss:0.04866	eval-mlogloss:0.02937
[47]	train-mlogloss:0.04841	eval-mlogloss:0.02953
[48]	train-mlogloss:0.04818	eval-mlogloss:0.02978
[49]	train-mlogloss:0.04794	eval-mlogloss:0.02995
[50]	train-mlogloss:0.04774	eval-mlogloss:0.02960
[51]	train-mlogloss:0.04746	eval-mlogloss:0.02965
[52]	train-mlogloss:0.04729	eval-mlogloss:0.02873
[53]	train-mlogloss:0.04723	eval-mlogloss:0.02887
[54]	train-mlogloss:0.04700	eval-mlogloss:0.02924
[55]	train-mlogloss:0.04681	eval-mlogloss:0.03002
[56]	train-mlogloss:0.04668	eval-mlogloss:0.03040
[57]	train-mlogloss:0.04659	eval-mlogloss:0.03052
[58]	train-mlogloss:0.04643	eval-mlogloss:0.03035
[59]	train-mlogloss:0.04625	eval-mlogloss:0.02956
[60]	train-mlogloss:0.04613	eval-mlogloss:0.02883
[61]	train-mlogloss:0.04598	eval-mlogloss:0.02876
[62]	train-mlogloss:0.04589	eval-mlogloss:0.02918
[63]	train-mlogloss:0.04573	eval-mlogloss:0.02851

[I 2025-06-10 11:13:39,891] Trial 3 pruned. Trial was pruned at iteration 64.

[0]	train-mlogloss:1.05957	eval-mlogloss:1.06001
[1]	train-mlogloss:1.03608	eval-mlogloss:1.04159
[2]	train-mlogloss:1.00898	eval-mlogloss:1.01960
[3]	train-mlogloss:0.96899	eval-mlogloss:0.97522
[4]	train-mlogloss:0.95100	eval-mlogloss:0.95994
[5]	train-mlogloss:0.92406	eval-mlogloss:0.93714
[6]	train-mlogloss:0.88782	eval-mlogloss:0.89631
[7]	train-mlogloss:0.85091	eval-mlogloss:0.85528
[8]	train-mlogloss:0.83371	eval-mlogloss:0.84216
[9]	train-mlogloss:0.79801	eval-mlogloss:0.80434
[10]	train-mlogloss:0.77109	eval-mlogloss:0.77573
[11]	train-mlogloss:0.75677	eval-mlogloss:0.76565
[12]	train-mlogloss:0.72934	eval-mlogloss:0.73715
[13]	train-mlogloss:0.70831	eval-mlogloss:0.71502
[14]	train-mlogloss:0.68093	eval-mlogloss:0.68436
[15]	train-mlogloss:0.66417	eval-mlogloss:0.67113
[16]	train-mlogloss:0.65144	eval-mlogloss:0.65965
[17]	train-mlogloss:0.63192	eval-mlogloss:0.64065
[18]	train-mlogloss:0.61210	eval-mlogloss:0.62087
[19]	train-mlogloss:0.60534	eval-mlogloss:0.61495
[20]	train-mlogloss:0.59863	eval-mlogloss:0.61005
[21]	train-mlogloss:0.58277	eval-mlogloss:0.59298
[22]	train-mlogloss:0.56093	eval-mlogloss:0.56787
[23]	train-mlogloss:0.54025	eval-mlogloss:0.54540
[24]	train-mlogloss:0.52425	eval-mlogloss:0.52621
[25]	train-mlogloss:0.50664	eval-mlogloss:0.50605
[26]	train-mlogloss:0.50136	eval-mlogloss:0.50056
[27]	train-mlogloss:0.48611	eval-mlogloss:0.48280
[28]	train-mlogloss:0.47662	eval-mlogloss:0.47586
[29]	train-mlogloss:0.46705	eval-mlogloss:0.46562
[30]	train-mlogloss:0.46019	eval-mlogloss:0.45887
[31]	train-mlogloss:0.44861	eval-mlogloss:0.44497
[32]	train-mlogloss:0.43395	eval-mlogloss:0.42797
[33]	train-mlogloss:0.42885	eval-mlogloss:0.42295
[34]	train-mlogloss:0.41988	eval-mlogloss:0.41425
[35]	train-mlogloss:0.41042	eval-mlogloss:0.40414
[36]	train-mlogloss:0.40165	eval-mlogloss:0.39737
[37]	train-mlogloss:0.38942	eval-mlogloss:0.38413
[38]	train-mlogloss:0.38104	eval-mlogloss:0.37523
[39]	train-mlogloss:0.37135	eval-mlogloss:0.36579
[40]	train-mlogloss:0.36464	eval-mlogloss:0.35983
[41]	train-mlogloss:0.35625	eval-mlogloss:0.35043
[42]	train-mlogloss:0.34741	eval-mlogloss:0.33957
[43]	train-mlogloss:0.33987	eval-mlogloss:0.33115
[44]	train-mlogloss:0.33244	eval-mlogloss:0.32444
[45]	train-mlogloss:0.32211	eval-mlogloss:0.31375
[46]	train-mlogloss:0.31943	eval-mlogloss:0.31025
[47]	train-mlogloss:0.31335	eval-mlogloss:0.30315
[48]	train-mlogloss:0.30691	eval-mlogloss:0.29663
[49]	train-mlogloss:0.30081	eval-mlogloss:0.29030
[50]	train-mlogloss:0.29336	eval-mlogloss:0.28066
[51]	train-mlogloss:0.28688	eval-mlogloss:0.27425
[52]	train-mlogloss:0.28234	eval-mlogloss:0.27003
[53]	train-mlogloss:0.27505	eval-mlogloss:0.26233
[54]	train-mlogloss:0.27102	eval-mlogloss:0.25776
[55]	train-mlogloss:0.26921	eval-mlogloss:0.25774
[56]	train-mlogloss:0.26471	eval-mlogloss:0.25243
[57]	train-mlogloss:0.25953	eval-mlogloss:0.24799
[58]	train-mlogloss:0.25478	eval-mlogloss:0.24260
[59]	train-mlogloss:0.24768	eval-mlogloss:0.23279
[60]	train-mlogloss:0.24268	eval-mlogloss:0.22943
[61]	train-mlogloss:0.23961	eval-mlogloss:0.22693
[62]	train-mlogloss:0.23361	eval-mlogloss:0.21922
[63]	train-mlogloss:0.23124	eval-mlogloss:0.21816
[64]	train-mlogloss:0.22748	eval-mlogloss:0.21394
[65]	train-mlogloss:0.22482	eval-mlogloss:0.21017
[66]	train-mlogloss:0.21928	eval-mlogloss:0.20402
[67]	train-mlogloss:0.21605	eval-mlogloss:0.20076
[68]	train-mlogloss:0.21158	eval-mlogloss:0.19664
[69]	train-mlogloss:0.20853	eval-mlogloss:0.19500
[70]	train-mlogloss:0.20729	eval-mlogloss:0.19382
[71]	train-mlogloss:0.20214	eval-mlogloss:0.18687
[72]	train-mlogloss:0.20109	eval-mlogloss:0.18800
[73]	train-mlogloss:0.19795	eval-mlogloss:0.18428
[74]	train-mlogloss:0.19338	eval-mlogloss:0.17924
[75]	train-mlogloss:0.19069	eval-mlogloss:0.17691
[76]	train-mlogloss:0.18979	eval-mlogloss:0.17686
[77]	train-mlogloss:0.18619	eval-mlogloss:0.17391
[78]	train-mlogloss:0.18286	eval-mlogloss:0.17041
[79]	train-mlogloss:0.18007	eval-mlogloss:0.16697
[80]	train-mlogloss:0.17841	eval-mlogloss:0.16632
[81]	train-mlogloss:0.17716	eval-mlogloss:0.16519
[82]	train-mlogloss:0.17424	eval-mlogloss:0.16222
[83]	train-mlogloss:0.17224	eval-mlogloss:0.15933
[84]	train-mlogloss:0.16922	eval-mlogloss:0.15645
[85]	train-mlogloss:0.16773	eval-mlogloss:0.15492
[86]	train-mlogloss:0.16559	eval-mlogloss:0.15287
[87]	train-mlogloss:0.16302	eval-mlogloss:0.14992
[88]	train-mlogloss:0.16110	eval-mlogloss:0.14805
[89]	train-mlogloss:0.15856	eval-mlogloss:0.14524
[90]	train-mlogloss:0.15735	eval-mlogloss:0.14383
[91]	train-mlogloss:0.15560	eval-mlogloss:0.14070
[92]	train-mlogloss:0.15433	eval-mlogloss:0.13968
[93]	train-mlogloss:0.15287	eval-mlogloss:0.13826
[94]	train-mlogloss:0.14967	eval-mlogloss:0.13438
[95]	train-mlogloss:0.14746	eval-mlogloss:0.13110
[96]	train-mlogloss:0.14569	eval-mlogloss:0.12984
[97]	train-mlogloss:0.14397	eval-mlogloss:0.12853
[98]	train-mlogloss:0.14179	eval-mlogloss:0.12486
[99]	train-mlogloss:0.14130	eval-mlogloss:0.12497
[100]	train-mlogloss:0.14008	eval-mlogloss:0.12463
[101]	train-mlogloss:0.13885	eval-mlogloss:0.12384
[102]	train-mlogloss:0.13708	eval-mlogloss:0.12150
[103]	train-mlogloss:0.13530	eval-mlogloss:0.12043
[104]	train-mlogloss:0.13357	eval-mlogloss:0.11826
[105]	train-mlogloss:0.13144	eval-mlogloss:0.11467
[106]	train-mlogloss:0.12943	eval-mlogloss:0.11157
[107]	train-mlogloss:0.12894	eval-mlogloss:0.11112
[108]	train-mlogloss:0.12723	eval-mlogloss:0.10921
[109]	train-mlogloss:0.12602	eval-mlogloss:0.10778
[110]	train-mlogloss:0.12506	eval-mlogloss:0.10632
[111]	train-mlogloss:0.12293	eval-mlogloss:0.10306
[112]	train-mlogloss:0.12185	eval-mlogloss:0.10189
[113]	train-mlogloss:0.12070	eval-mlogloss:0.09989
[114]	train-mlogloss:0.11938	eval-mlogloss:0.09771
[115]	train-mlogloss:0.11759	eval-mlogloss:0.09529
[116]	train-mlogloss:0.11725	eval-mlogloss:0.09537
[117]	train-mlogloss:0.11597	eval-mlogloss:0.09301
[118]	train-mlogloss:0.11582	eval-mlogloss:0.09309
[119]	train-mlogloss:0.11480	eval-mlogloss:0.09174
[120]	train-mlogloss:0.11390	eval-mlogloss:0.09038
[121]	train-mlogloss:0.11231	eval-mlogloss:0.08791
[122]	train-mlogloss:0.11177	eval-mlogloss:0.08751
[123]	train-mlogloss:0.11075	eval-mlogloss:0.08625
[124]	train-mlogloss:0.10998	eval-mlogloss:0.08540
[125]	train-mlogloss:0.10933	eval-mlogloss:0.08470
[126]	train-mlogloss:0.10829	eval-mlogloss:0.08409
[127]	train-mlogloss:0.10768	eval-mlogloss:0.08378
[128]	train-mlogloss:0.10659	eval-mlogloss:0.08225
[129]	train-mlogloss:0.10569	eval-mlogloss:0.08071
[130]	train-mlogloss:0.10513	eval-mlogloss:0.07971
[131]	train-mlogloss:0.10430	eval-mlogloss:0.07798
[132]	train-mlogloss:0.10356	eval-mlogloss:0.07758
[133]	train-mlogloss:0.10315	eval-mlogloss:0.07714
[134]	train-mlogloss:0.10246	eval-mlogloss:0.07645
[135]	train-mlogloss:0.10152	eval-mlogloss:0.07524
[136]	train-mlogloss:0.10130	eval-mlogloss:0.07473
[137]	train-mlogloss:0.10040	eval-mlogloss:0.07320
[138]	train-mlogloss:0.09951	eval-mlogloss:0.07239
[139]	train-mlogloss:0.09924	eval-mlogloss:0.07230
[140]	train-mlogloss:0.09854	eval-mlogloss:0.07117
[141]	train-mlogloss:0.09749	eval-mlogloss:0.06961
[142]	train-mlogloss:0.09717	eval-mlogloss:0.06913
[143]	train-mlogloss:0.09666	eval-mlogloss:0.06829
[144]	train-mlogloss:0.09649	eval-mlogloss:0.06774
[145]	train-mlogloss:0.09648	eval-mlogloss:0.06759
[146]	train-mlogloss:0.09563	eval-mlogloss:0.06666
[147]	train-mlogloss:0.09531	eval-mlogloss:0.06581
[148]	train-mlogloss:0.09434	eval-mlogloss:0.06368
[149]	train-mlogloss:0.09400	eval-mlogloss:0.06322
[150]	train-mlogloss:0.09396	eval-mlogloss:0.06367
[151]	train-mlogloss:0.09405	eval-mlogloss:0.06407
[152]	train-mlogloss:0.09376	eval-mlogloss:0.06295
[153]	train-mlogloss:0.09312	eval-mlogloss:0.06220
[154]	train-mlogloss:0.09247	eval-mlogloss:0.06137
[155]	train-mlogloss:0.09209	eval-mlogloss:0.06121
[156]	train-mlogloss:0.09194	eval-mlogloss:0.06072
[157]	train-mlogloss:0.09190	eval-mlogloss:0.06041
[158]	train-mlogloss:0.09143	eval-mlogloss:0.05927
[159]	train-mlogloss:0.09104	eval-mlogloss:0.05937
[160]	train-mlogloss:0.09063	eval-mlogloss:0.05954
[161]	train-mlogloss:0.09044	eval-mlogloss:0.05974
[162]	train-mlogloss:0.09053	eval-mlogloss:0.06034
[163]	train-mlogloss:0.09033	eval-mlogloss:0.06042
[164]	train-mlogloss:0.09029	eval-mlogloss:0.06026
[165]	train-mlogloss:0.08986	eval-mlogloss:0.06058
[166]	train-mlogloss:0.08954	eval-mlogloss:0.06038
[167]	train-mlogloss:0.08922	eval-mlogloss:0.05990
[168]	train-mlogloss:0.08912	eval-mlogloss:0.05989
[169]	train-mlogloss:0.08884	eval-mlogloss:0.05956
[170]	train-mlogloss:0.08877	eval-mlogloss:0.05916
[171]	train-mlogloss:0.08838	eval-mlogloss:0.05822
[172]	train-mlogloss:0.08774	eval-mlogloss:0.05763
[173]	train-mlogloss:0.08735	eval-mlogloss:0.05716
[174]	train-mlogloss:0.08734	eval-mlogloss:0.05696
[175]	train-mlogloss:0.08677	eval-mlogloss:0.05654
[176]	train-mlogloss:0.08649	eval-mlogloss:0.05677
[177]	train-mlogloss:0.08633	eval-mlogloss:0.05656
[178]	train-mlogloss:0.08602	eval-mlogloss:0.05609
[179]	train-mlogloss:0.08588	eval-mlogloss:0.05591
[180]	train-mlogloss:0.08571	eval-mlogloss:0.05530
[181]	train-mlogloss:0.08577	eval-mlogloss:0.05536
[182]	train-mlogloss:0.08564	eval-mlogloss:0.05516
[183]	train-mlogloss:0.08519	eval-mlogloss:0.05478
[184]	train-mlogloss:0.08456	eval-mlogloss:0.05411
[185]	train-mlogloss:0.08457	eval-mlogloss:0.05436
[186]	train-mlogloss:0.08435	eval-mlogloss:0.05473
[187]	train-mlogloss:0.08438	eval-mlogloss:0.05458
[188]	train-mlogloss:0.08420	eval-mlogloss:0.05488
[189]	train-mlogloss:0.08395	eval-mlogloss:0.05436
[190]	train-mlogloss:0.08391	eval-mlogloss:0.05454
[191]	train-mlogloss:0.08393	eval-mlogloss:0.05421
[192]	train-mlogloss:0.08354	eval-mlogloss:0.05365
[193]	train-mlogloss:0.08352	eval-mlogloss:0.05364
[194]	train-mlogloss:0.08342	eval-mlogloss:0.05372
[195]	train-mlogloss:0.08321	eval-mlogloss:0.05327
[196]	train-mlogloss:0.08278	eval-mlogloss:0.05221
[197]	train-mlogloss:0.08281	eval-mlogloss:0.05257
[198]	train-mlogloss:0.08264	eval-mlogloss:0.05248
[199]	train-mlogloss:0.08233	eval-mlogloss:0.05170
[200]	train-mlogloss:0.08207	eval-mlogloss:0.05188
[201]	train-mlogloss:0.08210	eval-mlogloss:0.05188
[202]	train-mlogloss:0.08206	eval-mlogloss:0.05229
[203]	train-mlogloss:0.08201	eval-mlogloss:0.05229
[204]	train-mlogloss:0.08177	eval-mlogloss:0.05209
[205]	train-mlogloss:0.08116	eval-mlogloss:0.05095
[206]	train-mlogloss:0.08108	eval-mlogloss:0.05083
[207]	train-mlogloss:0.08081	eval-mlogloss:0.05042
[208]	train-mlogloss:0.08069	eval-mlogloss:0.05073
[209]	train-mlogloss:0.08037	eval-mlogloss:0.05041
[210]	train-mlogloss:0.08025	eval-mlogloss:0.05023
[211]	train-mlogloss:0.08012	eval-mlogloss:0.05049
[212]	train-mlogloss:0.07978	eval-mlogloss:0.04950
[213]	train-mlogloss:0.07950	eval-mlogloss:0.04862
[214]	train-mlogloss:0.07931	eval-mlogloss:0.04849
[215]	train-mlogloss:0.07926	eval-mlogloss:0.04868
[216]	train-mlogloss:0.07907	eval-mlogloss:0.04846
[217]	train-mlogloss:0.07890	eval-mlogloss:0.04781
[218]	train-mlogloss:0.07878	eval-mlogloss:0.04768
[219]	train-mlogloss:0.07871	eval-mlogloss:0.04773
[220]	train-mlogloss:0.07822	eval-mlogloss:0.04675
[221]	train-mlogloss:0.07815	eval-mlogloss:0.04687
[222]	train-mlogloss:0.07788	eval-mlogloss:0.04616
[223]	train-mlogloss:0.07787	eval-mlogloss:0.04624
[224]	train-mlogloss:0.07750	eval-mlogloss:0.04568
[225]	train-mlogloss:0.07716	eval-mlogloss:0.04559
[226]	train-mlogloss:0.07716	eval-mlogloss:0.04607
[227]	train-mlogloss:0.07703	eval-mlogloss:0.04593
[228]	train-mlogloss:0.07695	eval-mlogloss:0.04586
[229]	train-mlogloss:0.07685	eval-mlogloss:0.04555
[230]	train-mlogloss:0.07666	eval-mlogloss:0.04550
[231]	train-mlogloss:0.07657	eval-mlogloss:0.04518
[232]	train-mlogloss:0.07650	eval-mlogloss:0.04525
[233]	train-mlogloss:0.07628	eval-mlogloss:0.04504
[234]	train-mlogloss:0.07630	eval-mlogloss:0.04494
[235]	train-mlogloss:0.07615	eval-mlogloss:0.04474
[236]	train-mlogloss:0.07593	eval-mlogloss:0.04419
[237]	train-mlogloss:0.07585	eval-mlogloss:0.04392
[238]	train-mlogloss:0.07563	eval-mlogloss:0.04380
[239]	train-mlogloss:0.07556	eval-mlogloss:0.04358
[240]	train-mlogloss:0.07548	eval-mlogloss:0.04335
[241]	train-mlogloss:0.07523	eval-mlogloss:0.04388
[242]	train-mlogloss:0.07509	eval-mlogloss:0.04401
[243]	train-mlogloss:0.07499	eval-mlogloss:0.04405
[244]	train-mlogloss:0.07512	eval-mlogloss:0.04426
[245]	train-mlogloss:0.07506	eval-mlogloss:0.04408
[246]	train-mlogloss:0.07497	eval-mlogloss:0.04438
[247]	train-mlogloss:0.07462	eval-mlogloss:0.04383
[248]	train-mlogloss:0.07429	eval-mlogloss:0.04333
[249]	train-mlogloss:0.07428	eval-mlogloss:0.04323
[250]	train-mlogloss:0.07431	eval-mlogloss:0.04308
[251]	train-mlogloss:0.07432	eval-mlogloss:0.04317
[252]	train-mlogloss:0.07404	eval-mlogloss:0.04256
[253]	train-mlogloss:0.07394	eval-mlogloss:0.04268
[254]	train-mlogloss:0.07370	eval-mlogloss:0.04235
[255]	train-mlogloss:0.07344	eval-mlogloss:0.04230
[256]	train-mlogloss:0.07321	eval-mlogloss:0.04201
[257]	train-mlogloss:0.07292	eval-mlogloss:0.04146
[258]	train-mlogloss:0.07263	eval-mlogloss:0.04146
[259]	train-mlogloss:0.07270	eval-mlogloss:0.04159
[260]	train-mlogloss:0.07260	eval-mlogloss:0.04160
[261]	train-mlogloss:0.07241	eval-mlogloss:0.04134
[262]	train-mlogloss:0.07218	eval-mlogloss:0.04126
[263]	train-mlogloss:0.07220	eval-mlogloss:0.04128
[264]	train-mlogloss:0.07205	eval-mlogloss:0.04080
[265]	train-mlogloss:0.07184	eval-mlogloss:0.04078
[266]	train-mlogloss:0.07170	eval-mlogloss:0.04045
[267]	train-mlogloss:0.07156	eval-mlogloss:0.04052
[268]	train-mlogloss:0.07124	eval-mlogloss:0.03992
[269]	train-mlogloss:0.07114	eval-mlogloss:0.03992
[270]	train-mlogloss:0.07089	eval-mlogloss:0.03944
[271]	train-mlogloss:0.07067	eval-mlogloss:0.03864
[272]	train-mlogloss:0.07052	eval-mlogloss:0.03866
[273]	train-mlogloss:0.07038	eval-mlogloss:0.03840
[274]	train-mlogloss:0.07041	eval-mlogloss:0.03829
[275]	train-mlogloss:0.07037	eval-mlogloss:0.03864
[276]	train-mlogloss:0.07039	eval-mlogloss:0.03881
[277]	train-mlogloss:0.07043	eval-mlogloss:0.03874
[278]	train-mlogloss:0.07031	eval-mlogloss:0.03902
[279]	train-mlogloss:0.06996	eval-mlogloss:0.03857
[280]	train-mlogloss:0.06978	eval-mlogloss:0.03809
[281]	train-mlogloss:0.06964	eval-mlogloss:0.03802
[282]	train-mlogloss:0.06962	eval-mlogloss:0.03806
[283]	train-mlogloss:0.06965	eval-mlogloss:0.03830
[284]	train-mlogloss:0.06944	eval-mlogloss:0.03855
[285]	train-mlogloss:0.06949	eval-mlogloss:0.03821
[286]	train-mlogloss:0.06918	eval-mlogloss:0.03807
[287]	train-mlogloss:0.06910	eval-mlogloss:0.03822
[288]	train-mlogloss:0.06900	eval-mlogloss:0.03823
[289]	train-mlogloss:0.06913	eval-mlogloss:0.03822
[290]	train-mlogloss:0.06899	eval-mlogloss:0.03782
[291]	train-mlogloss:0.06888	eval-mlogloss:0.03774
[292]	train-mlogloss:0.06891	eval-mlogloss:0.03763
[293]	train-mlogloss:0.06878	eval-mlogloss:0.03738
[294]	train-mlogloss:0.06883	eval-mlogloss:0.03756
[295]	train-mlogloss:0.06876	eval-mlogloss:0.03752
[296]	train-mlogloss:0.06864	eval-mlogloss:0.03783
[297]	train-mlogloss:0.06860	eval-mlogloss:0.03798
[298]	train-mlogloss:0.06828	eval-mlogloss:0.03742
[299]	train-mlogloss:0.06815	eval-mlogloss:0.03770

[I 2025-06-10 11:13:43,084] Trial 4 finished with value: 1.0 and parameters: {'lambda': 0.04517404775194881, 'alpha': 2.932870250105054e-07, 'eta': 0.04001531457900299, 'gamma': 1.4244260948840395e-08, 'max_depth': 5, 'min_child_weight': 1, 'subsample': 0.42448067205382034, 'colsample_bytree': 0.4943064180932379}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.86207	eval-mlogloss:0.86315
[1]	train-mlogloss:0.68899	eval-mlogloss:0.67761

[I 2025-06-10 11:13:43,104] Trial 5 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.79392	eval-mlogloss:0.79763

[I 2025-06-10 11:13:43,151] Trial 6 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.92872	eval-mlogloss:0.93000

[I 2025-06-10 11:13:43,193] Trial 7 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.97949	eval-mlogloss:0.97706
[1]	train-mlogloss:0.88047	eval-mlogloss:0.87135
[2]	train-mlogloss:0.79399	eval-mlogloss:0.78103
[3]	train-mlogloss:0.71886	eval-mlogloss:0.70199
[4]	train-mlogloss:0.65708	eval-mlogloss:0.63576

[I 2025-06-10 11:13:43,271] Trial 8 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.00077	eval-mlogloss:0.99853
[1]	train-mlogloss:0.91554	eval-mlogloss:0.90607
[2]	train-mlogloss:0.84059	eval-mlogloss:0.82523
[3]	train-mlogloss:0.77191	eval-mlogloss:0.75315
[4]	train-mlogloss:0.71510	eval-mlogloss:0.69344

[I 2025-06-10 11:13:43,319] Trial 9 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.96454	eval-mlogloss:0.95686
[1]	train-mlogloss:0.90224	eval-mlogloss:0.87925

[I 2025-06-10 11:13:43,461] Trial 10 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.82038	eval-mlogloss:0.80952
[1]	train-mlogloss:0.72601	eval-mlogloss:0.69797

[I 2025-06-10 11:13:43,571] Trial 11 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.89740	eval-mlogloss:0.88996
[1]	train-mlogloss:0.79521	eval-mlogloss:0.80113

[I 2025-06-10 11:13:43,747] Trial 12 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.83445	eval-mlogloss:0.84223

[I 2025-06-10 11:13:43,865] Trial 13 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.85158	eval-mlogloss:0.83940

[I 2025-06-10 11:13:44,112] Trial 14 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.93138	eval-mlogloss:0.92623

[I 2025-06-10 11:13:44,303] Trial 15 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.07907	eval-mlogloss:1.07825
[1]	train-mlogloss:1.06822	eval-mlogloss:1.06743
[2]	train-mlogloss:1.05136	eval-mlogloss:1.05019
[3]	train-mlogloss:1.03266	eval-mlogloss:1.03123
[4]	train-mlogloss:1.01475	eval-mlogloss:1.01293
[5]	train-mlogloss:0.99717	eval-mlogloss:0.99451
[6]	train-mlogloss:0.98044	eval-mlogloss:0.97655
[7]	train-mlogloss:0.96388	eval-mlogloss:0.95913
[8]	train-mlogloss:0.94799	eval-mlogloss:0.94213
[9]	train-mlogloss:0.93229	eval-mlogloss:0.92580
[10]	train-mlogloss:0.91845	eval-mlogloss:0.91154
[11]	train-mlogloss:0.90328	eval-mlogloss:0.89602
[12]	train-mlogloss:0.89063	eval-mlogloss:0.88296
[13]	train-mlogloss:0.87609	eval-mlogloss:0.86770
[14]	train-mlogloss:0.86207	eval-mlogloss:0.85245
[15]	train-mlogloss:0.85060	eval-mlogloss:0.84060
[16]	train-mlogloss:0.83913	eval-mlogloss:0.82888
[17]	train-mlogloss:0.82578	eval-mlogloss:0.81494
[18]	train-mlogloss:0.81497	eval-mlogloss:0.80386
[19]	train-mlogloss:0.80338	eval-mlogloss:0.79240
[20]	train-mlogloss:0.79319	eval-mlogloss:0.78193
[21]	train-mlogloss:0.78279	eval-mlogloss:0.77102
[22]	train-mlogloss:0.77075	eval-mlogloss:0.75785
[23]	train-mlogloss:0.75890	eval-mlogloss:0.74549
[24]	train-mlogloss:0.74733	eval-mlogloss:0.73311
[25]	train-mlogloss:0.73595	eval-mlogloss:0.72112
[26]	train-mlogloss:0.72591	eval-mlogloss:0.71024
[27]	train-mlogloss:0.71504	eval-mlogloss:0.69869
[28]	train-mlogloss:0.70461	eval-mlogloss:0.68772
[29]	train-mlogloss:0.69593	eval-mlogloss:0.67849
[30]	train-mlogloss:0.68969	eval-mlogloss:0.67259
[31]	train-mlogloss:0.68168	eval-mlogloss:0.66431
[32]	train-mlogloss:0.67166	eval-mlogloss:0.65378
[33]	train-mlogloss:0.66165	eval-mlogloss:0.64308
[34]	train-mlogloss:0.65431	eval-mlogloss:0.63590
[35]	train-mlogloss:0.64501	eval-mlogloss:0.62574
[36]	train-mlogloss:0.63673	eval-mlogloss:0.61721
[37]	train-mlogloss:0.62753	eval-mlogloss:0.60746
[38]	train-mlogloss:0.61886	eval-mlogloss:0.59800
[39]	train-mlogloss:0.61014	eval-mlogloss:0.58925
[40]	train-mlogloss:0.60316	eval-mlogloss:0.58182
[41]	train-mlogloss:0.59468	eval-mlogloss:0.57259
[42]	train-mlogloss:0.58650	eval-mlogloss:0.56372
[43]	train-mlogloss:0.57829	eval-mlogloss:0.55520
[44]	train-mlogloss:0.57225	eval-mlogloss:0.54866
[45]	train-mlogloss:0.56436	eval-mlogloss:0.54033
[46]	train-mlogloss:0.55668	eval-mlogloss:0.53242
[47]	train-mlogloss:0.54984	eval-mlogloss:0.52539
[48]	train-mlogloss:0.54250	eval-mlogloss:0.51790
[49]	train-mlogloss:0.53507	eval-mlogloss:0.50992
[50]	train-mlogloss:0.52797	eval-mlogloss:0.50214
[51]	train-mlogloss:0.52166	eval-mlogloss:0.49517
[52]	train-mlogloss:0.51714	eval-mlogloss:0.49060
[53]	train-mlogloss:0.51047	eval-mlogloss:0.48350
[54]	train-mlogloss:0.50544	eval-mlogloss:0.47817
[55]	train-mlogloss:0.49985	eval-mlogloss:0.47266
[56]	train-mlogloss:0.49455	eval-mlogloss:0.46690
[57]	train-mlogloss:0.48932	eval-mlogloss:0.46147
[58]	train-mlogloss:0.48454	eval-mlogloss:0.45662
[59]	train-mlogloss:0.47821	eval-mlogloss:0.44993
[60]	train-mlogloss:0.47215	eval-mlogloss:0.44341
[61]	train-mlogloss:0.46715	eval-mlogloss:0.43814
[62]	train-mlogloss:0.46122	eval-mlogloss:0.43183
[63]	train-mlogloss:0.45547	eval-mlogloss:0.42559
[64]	train-mlogloss:0.44973	eval-mlogloss:0.41940
[65]	train-mlogloss:0.44408	eval-mlogloss:0.41362
[66]	train-mlogloss:0.43845	eval-mlogloss:0.40746
[67]	train-mlogloss:0.43430	eval-mlogloss:0.40315
[68]	train-mlogloss:0.43023	eval-mlogloss:0.39906
[69]	train-mlogloss:0.42570	eval-mlogloss:0.39440
[70]	train-mlogloss:0.42117	eval-mlogloss:0.38958
[71]	train-mlogloss:0.41591	eval-mlogloss:0.38371
[72]	train-mlogloss:0.41284	eval-mlogloss:0.38039
[73]	train-mlogloss:0.40780	eval-mlogloss:0.37534
[74]	train-mlogloss:0.40300	eval-mlogloss:0.37040
[75]	train-mlogloss:0.39800	eval-mlogloss:0.36506
[76]	train-mlogloss:0.39516	eval-mlogloss:0.36201
[77]	train-mlogloss:0.39042	eval-mlogloss:0.35722
[78]	train-mlogloss:0.38652	eval-mlogloss:0.35303
[79]	train-mlogloss:0.38195	eval-mlogloss:0.34795
[80]	train-mlogloss:0.37811	eval-mlogloss:0.34359
[81]	train-mlogloss:0.37355	eval-mlogloss:0.33896
[82]	train-mlogloss:0.36949	eval-mlogloss:0.33491
[83]	train-mlogloss:0.36571	eval-mlogloss:0.33042
[84]	train-mlogloss:0.36151	eval-mlogloss:0.32597
[85]	train-mlogloss:0.35888	eval-mlogloss:0.32344
[86]	train-mlogloss:0.35475	eval-mlogloss:0.31880
[87]	train-mlogloss:0.35162	eval-mlogloss:0.31558
[88]	train-mlogloss:0.34812	eval-mlogloss:0.31170
[89]	train-mlogloss:0.34422	eval-mlogloss:0.30755
[90]	train-mlogloss:0.34062	eval-mlogloss:0.30375
[91]	train-mlogloss:0.33746	eval-mlogloss:0.30023
[92]	train-mlogloss:0.33455	eval-mlogloss:0.29685
[93]	train-mlogloss:0.33079	eval-mlogloss:0.29280
[94]	train-mlogloss:0.32705	eval-mlogloss:0.28889
[95]	train-mlogloss:0.32431	eval-mlogloss:0.28586
[96]	train-mlogloss:0.32101	eval-mlogloss:0.28199
[97]	train-mlogloss:0.31776	eval-mlogloss:0.27835
[98]	train-mlogloss:0.31487	eval-mlogloss:0.27530
[99]	train-mlogloss:0.31180	eval-mlogloss:0.27179
[100]	train-mlogloss:0.30945	eval-mlogloss:0.26918
[101]	train-mlogloss:0.30633	eval-mlogloss:0.26580
[102]	train-mlogloss:0.30318	eval-mlogloss:0.26244
[103]	train-mlogloss:0.30079	eval-mlogloss:0.25991
[104]	train-mlogloss:0.29849	eval-mlogloss:0.25750
[105]	train-mlogloss:0.29613	eval-mlogloss:0.25457
[106]	train-mlogloss:0.29314	eval-mlogloss:0.25151
[107]	train-mlogloss:0.29043	eval-mlogloss:0.24846
[108]	train-mlogloss:0.28775	eval-mlogloss:0.24524
[109]	train-mlogloss:0.28557	eval-mlogloss:0.24281
[110]	train-mlogloss:0.28294	eval-mlogloss:0.23966
[111]	train-mlogloss:0.28041	eval-mlogloss:0.23671
[112]	train-mlogloss:0.27850	eval-mlogloss:0.23453
[113]	train-mlogloss:0.27670	eval-mlogloss:0.23237
[114]	train-mlogloss:0.27424	eval-mlogloss:0.22968
[115]	train-mlogloss:0.27191	eval-mlogloss:0.22681
[116]	train-mlogloss:0.27017	eval-mlogloss:0.22501
[117]	train-mlogloss:0.26805	eval-mlogloss:0.22237
[118]	train-mlogloss:0.26593	eval-mlogloss:0.21988
[119]	train-mlogloss:0.26406	eval-mlogloss:0.21801
[120]	train-mlogloss:0.26236	eval-mlogloss:0.21599
[121]	train-mlogloss:0.26002	eval-mlogloss:0.21332
[122]	train-mlogloss:0.25822	eval-mlogloss:0.21160
[123]	train-mlogloss:0.25678	eval-mlogloss:0.21002
[124]	train-mlogloss:0.25511	eval-mlogloss:0.20821
[125]	train-mlogloss:0.25350	eval-mlogloss:0.20625
[126]	train-mlogloss:0.25198	eval-mlogloss:0.20503
[127]	train-mlogloss:0.25051	eval-mlogloss:0.20335
[128]	train-mlogloss:0.24847	eval-mlogloss:0.20094
[129]	train-mlogloss:0.24667	eval-mlogloss:0.19877
[130]	train-mlogloss:0.24481	eval-mlogloss:0.19656
[131]	train-mlogloss:0.24326	eval-mlogloss:0.19466
[132]	train-mlogloss:0.24170	eval-mlogloss:0.19284
[133]	train-mlogloss:0.24042	eval-mlogloss:0.19153
[134]	train-mlogloss:0.23884	eval-mlogloss:0.18968
[135]	train-mlogloss:0.23735	eval-mlogloss:0.18825
[136]	train-mlogloss:0.23566	eval-mlogloss:0.18631
[137]	train-mlogloss:0.23394	eval-mlogloss:0.18435
[138]	train-mlogloss:0.23267	eval-mlogloss:0.18291
[139]	train-mlogloss:0.23125	eval-mlogloss:0.18141
[140]	train-mlogloss:0.22995	eval-mlogloss:0.17984
[141]	train-mlogloss:0.22818	eval-mlogloss:0.17788
[142]	train-mlogloss:0.22682	eval-mlogloss:0.17645
[143]	train-mlogloss:0.22551	eval-mlogloss:0.17492
[144]	train-mlogloss:0.22423	eval-mlogloss:0.17346
[145]	train-mlogloss:0.22265	eval-mlogloss:0.17168
[146]	train-mlogloss:0.22115	eval-mlogloss:0.17004
[147]	train-mlogloss:0.21976	eval-mlogloss:0.16835
[148]	train-mlogloss:0.21864	eval-mlogloss:0.16694
[149]	train-mlogloss:0.21743	eval-mlogloss:0.16556
[150]	train-mlogloss:0.21659	eval-mlogloss:0.16490
[151]	train-mlogloss:0.21558	eval-mlogloss:0.16362
[152]	train-mlogloss:0.21490	eval-mlogloss:0.16266
[153]	train-mlogloss:0.21354	eval-mlogloss:0.16122
[154]	train-mlogloss:0.21212	eval-mlogloss:0.15967
[155]	train-mlogloss:0.21122	eval-mlogloss:0.15871
[156]	train-mlogloss:0.21019	eval-mlogloss:0.15744
[157]	train-mlogloss:0.20916	eval-mlogloss:0.15622
[158]	train-mlogloss:0.20864	eval-mlogloss:0.15549
[159]	train-mlogloss:0.20763	eval-mlogloss:0.15424
[160]	train-mlogloss:0.20666	eval-mlogloss:0.15302
[161]	train-mlogloss:0.20642	eval-mlogloss:0.15267
[162]	train-mlogloss:0.20589	eval-mlogloss:0.15195
[163]	train-mlogloss:0.20537	eval-mlogloss:0.15141
[164]	train-mlogloss:0.20429	eval-mlogloss:0.15028
[165]	train-mlogloss:0.20369	eval-mlogloss:0.14942
[166]	train-mlogloss:0.20352	eval-mlogloss:0.14918
[167]	train-mlogloss:0.20293	eval-mlogloss:0.14855
[168]	train-mlogloss:0.20282	eval-mlogloss:0.14846
[169]	train-mlogloss:0.20217	eval-mlogloss:0.14777
[170]	train-mlogloss:0.20108	eval-mlogloss:0.14647
[171]	train-mlogloss:0.20060	eval-mlogloss:0.14582
[172]	train-mlogloss:0.20020	eval-mlogloss:0.14526
[173]	train-mlogloss:0.19969	eval-mlogloss:0.14470
[174]	train-mlogloss:0.19927	eval-mlogloss:0.14405
[175]	train-mlogloss:0.19887	eval-mlogloss:0.14363
[176]	train-mlogloss:0.19816	eval-mlogloss:0.14283
[177]	train-mlogloss:0.19777	eval-mlogloss:0.14241
[178]	train-mlogloss:0.19730	eval-mlogloss:0.14190
[179]	train-mlogloss:0.19666	eval-mlogloss:0.14126
[180]	train-mlogloss:0.19633	eval-mlogloss:0.14070
[181]	train-mlogloss:0.19581	eval-mlogloss:0.14014
[182]	train-mlogloss:0.19538	eval-mlogloss:0.13958
[183]	train-mlogloss:0.19521	eval-mlogloss:0.13934
[184]	train-mlogloss:0.19501	eval-mlogloss:0.13922
[185]	train-mlogloss:0.19488	eval-mlogloss:0.13903
[186]	train-mlogloss:0.19475	eval-mlogloss:0.13904
[187]	train-mlogloss:0.19463	eval-mlogloss:0.13888
[188]	train-mlogloss:0.19424	eval-mlogloss:0.13836
[189]	train-mlogloss:0.19380	eval-mlogloss:0.13777
[190]	train-mlogloss:0.19330	eval-mlogloss:0.13722
[191]	train-mlogloss:0.19297	eval-mlogloss:0.13669
[192]	train-mlogloss:0.19251	eval-mlogloss:0.13623
[193]	train-mlogloss:0.19240	eval-mlogloss:0.13609
[194]	train-mlogloss:0.19226	eval-mlogloss:0.13612
[195]	train-mlogloss:0.19188	eval-mlogloss:0.13562
[196]	train-mlogloss:0.19157	eval-mlogloss:0.13520
[197]	train-mlogloss:0.19127	eval-mlogloss:0.13480
[198]	train-mlogloss:0.19089	eval-mlogloss:0.13427
[199]	train-mlogloss:0.19051	eval-mlogloss:0.13379
[200]	train-mlogloss:0.19024	eval-mlogloss:0.13335
[201]	train-mlogloss:0.18985	eval-mlogloss:0.13274
[202]	train-mlogloss:0.18982	eval-mlogloss:0.13270
[203]	train-mlogloss:0.18958	eval-mlogloss:0.13228
[204]	train-mlogloss:0.18922	eval-mlogloss:0.13188
[205]	train-mlogloss:0.18889	eval-mlogloss:0.13140
[206]	train-mlogloss:0.18855	eval-mlogloss:0.13092
[207]	train-mlogloss:0.18813	eval-mlogloss:0.13038
[208]	train-mlogloss:0.18801	eval-mlogloss:0.13023
[209]	train-mlogloss:0.18761	eval-mlogloss:0.12979
[210]	train-mlogloss:0.18723	eval-mlogloss:0.12915
[211]	train-mlogloss:0.18709	eval-mlogloss:0.12913
[212]	train-mlogloss:0.18682	eval-mlogloss:0.12874
[213]	train-mlogloss:0.18657	eval-mlogloss:0.12844
[214]	train-mlogloss:0.18625	eval-mlogloss:0.12799
[215]	train-mlogloss:0.18597	eval-mlogloss:0.12759
[216]	train-mlogloss:0.18565	eval-mlogloss:0.12727
[217]	train-mlogloss:0.18564	eval-mlogloss:0.12717
[218]	train-mlogloss:0.18529	eval-mlogloss:0.12666
[219]	train-mlogloss:0.18524	eval-mlogloss:0.12661
[220]	train-mlogloss:0.18496	eval-mlogloss:0.12623
[221]	train-mlogloss:0.18480	eval-mlogloss:0.12624
[222]	train-mlogloss:0.18450	eval-mlogloss:0.12588
[223]	train-mlogloss:0.18446	eval-mlogloss:0.12586
[224]	train-mlogloss:0.18415	eval-mlogloss:0.12533
[225]	train-mlogloss:0.18390	eval-mlogloss:0.12498
[226]	train-mlogloss:0.18353	eval-mlogloss:0.12459
[227]	train-mlogloss:0.18317	eval-mlogloss:0.12422
[228]	train-mlogloss:0.18288	eval-mlogloss:0.12379
[229]	train-mlogloss:0.18274	eval-mlogloss:0.12361
[230]	train-mlogloss:0.18248	eval-mlogloss:0.12324
[231]	train-mlogloss:0.18243	eval-mlogloss:0.12315
[232]	train-mlogloss:0.18223	eval-mlogloss:0.12286
[233]	train-mlogloss:0.18189	eval-mlogloss:0.12239
[234]	train-mlogloss:0.18166	eval-mlogloss:0.12208
[235]	train-mlogloss:0.18159	eval-mlogloss:0.12206
[236]	train-mlogloss:0.18131	eval-mlogloss:0.12164
[237]	train-mlogloss:0.18103	eval-mlogloss:0.12124
[238]	train-mlogloss:0.18098	eval-mlogloss:0.12120
[239]	train-mlogloss:0.18071	eval-mlogloss:0.12078
[240]	train-mlogloss:0.18069	eval-mlogloss:0.12068
[241]	train-mlogloss:0.18059	eval-mlogloss:0.12070
[242]	train-mlogloss:0.18033	eval-mlogloss:0.12034
[243]	train-mlogloss:0.18031	eval-mlogloss:0.12033
[244]	train-mlogloss:0.18003	eval-mlogloss:0.11990
[245]	train-mlogloss:0.18001	eval-mlogloss:0.11985
[246]	train-mlogloss:0.17983	eval-mlogloss:0.11959
[247]	train-mlogloss:0.17956	eval-mlogloss:0.11917
[248]	train-mlogloss:0.17932	eval-mlogloss:0.11882
[249]	train-mlogloss:0.17908	eval-mlogloss:0.11849
[250]	train-mlogloss:0.17888	eval-mlogloss:0.11820
[251]	train-mlogloss:0.17885	eval-mlogloss:0.11818
[252]	train-mlogloss:0.17864	eval-mlogloss:0.11791
[253]	train-mlogloss:0.17860	eval-mlogloss:0.11789
[254]	train-mlogloss:0.17837	eval-mlogloss:0.11753
[255]	train-mlogloss:0.17817	eval-mlogloss:0.11725
[256]	train-mlogloss:0.17810	eval-mlogloss:0.11719
[257]	train-mlogloss:0.17800	eval-mlogloss:0.11726
[258]	train-mlogloss:0.17794	eval-mlogloss:0.11721
[259]	train-mlogloss:0.17794	eval-mlogloss:0.11721
[260]	train-mlogloss:0.17789	eval-mlogloss:0.11717
[261]	train-mlogloss:0.17788	eval-mlogloss:0.11716
[262]	train-mlogloss:0.17767	eval-mlogloss:0.11687
[263]	train-mlogloss:0.17766	eval-mlogloss:0.11687
[264]	train-mlogloss:0.17764	eval-mlogloss:0.11678
[265]	train-mlogloss:0.17763	eval-mlogloss:0.11676
[266]	train-mlogloss:0.17758	eval-mlogloss:0.11675
[267]	train-mlogloss:0.17736	eval-mlogloss:0.11639
[268]	train-mlogloss:0.17731	eval-mlogloss:0.11633
[269]	train-mlogloss:0.17706	eval-mlogloss:0.11595
[270]	train-mlogloss:0.17705	eval-mlogloss:0.11591
[271]	train-mlogloss:0.17692	eval-mlogloss:0.11574
[272]	train-mlogloss:0.17692	eval-mlogloss:0.11574
[273]	train-mlogloss:0.17687	eval-mlogloss:0.11568
[274]	train-mlogloss:0.17686	eval-mlogloss:0.11567
[275]	train-mlogloss:0.17685	eval-mlogloss:0.11564
[276]	train-mlogloss:0.17667	eval-mlogloss:0.11540
[277]	train-mlogloss:0.17659	eval-mlogloss:0.11540
[278]	train-mlogloss:0.17648	eval-mlogloss:0.11542
[279]	train-mlogloss:0.17643	eval-mlogloss:0.11539
[280]	train-mlogloss:0.17640	eval-mlogloss:0.11537
[281]	train-mlogloss:0.17631	eval-mlogloss:0.11527
[282]	train-mlogloss:0.17626	eval-mlogloss:0.11523
[283]	train-mlogloss:0.17623	eval-mlogloss:0.11520
[284]	train-mlogloss:0.17622	eval-mlogloss:0.11510
[285]	train-mlogloss:0.17612	eval-mlogloss:0.11516
[286]	train-mlogloss:0.17608	eval-mlogloss:0.11513
[287]	train-mlogloss:0.17581	eval-mlogloss:0.11481
[288]	train-mlogloss:0.17581	eval-mlogloss:0.11479
[289]	train-mlogloss:0.17560	eval-mlogloss:0.11453
[290]	train-mlogloss:0.17556	eval-mlogloss:0.11451
[291]	train-mlogloss:0.17556	eval-mlogloss:0.11450
[292]	train-mlogloss:0.17555	eval-mlogloss:0.11443
[293]	train-mlogloss:0.17546	eval-mlogloss:0.11430
[294]	train-mlogloss:0.17540	eval-mlogloss:0.11427
[295]	train-mlogloss:0.17534	eval-mlogloss:0.11421
[296]	train-mlogloss:0.17518	eval-mlogloss:0.11422
[297]	train-mlogloss:0.17517	eval-mlogloss:0.11421
[298]	train-mlogloss:0.17513	eval-mlogloss:0.11416
[299]	train-mlogloss:0.17512	eval-mlogloss:0.11415

[I 2025-06-10 11:13:47,291] Trial 16 finished with value: 1.0 and parameters: {'lambda': 1.485397088749998e-06, 'alpha': 7.39962917790959e-05, 'eta': 0.014970060167645627, 'gamma': 1.050573135315028e-05, 'max_depth': 5, 'min_child_weight': 7, 'subsample': 0.8349155506349758, 'colsample_bytree': 0.5996618204285751}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:0.79809	eval-mlogloss:0.78539
[1]	train-mlogloss:0.69518	eval-mlogloss:0.67268

[I 2025-06-10 11:13:47,409] Trial 17 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.92003	eval-mlogloss:0.92089
[1]	train-mlogloss:0.83851	eval-mlogloss:0.84996

[I 2025-06-10 11:13:47,505] Trial 18 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.89198	eval-mlogloss:0.88062
[1]	train-mlogloss:0.80858	eval-mlogloss:0.79366

[I 2025-06-10 11:13:47,597] Trial 19 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.97262	eval-mlogloss:0.96846
[1]	train-mlogloss:0.92266	eval-mlogloss:0.91071
[2]	train-mlogloss:0.84254	eval-mlogloss:0.83077
[3]	train-mlogloss:0.75892	eval-mlogloss:0.73853

[I 2025-06-10 11:13:47,697] Trial 20 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.07745	eval-mlogloss:1.07689
[1]	train-mlogloss:1.06473	eval-mlogloss:1.06427
[2]	train-mlogloss:1.04543	eval-mlogloss:1.04331
[3]	train-mlogloss:1.02526	eval-mlogloss:1.02120
[4]	train-mlogloss:1.00601	eval-mlogloss:1.00186
[5]	train-mlogloss:0.98679	eval-mlogloss:0.98152
[6]	train-mlogloss:0.96783	eval-mlogloss:0.96126
[7]	train-mlogloss:0.95056	eval-mlogloss:0.94402
[8]	train-mlogloss:0.93300	eval-mlogloss:0.92522
[9]	train-mlogloss:0.91541	eval-mlogloss:0.90734
[10]	train-mlogloss:0.89887	eval-mlogloss:0.88996
[11]	train-mlogloss:0.88265	eval-mlogloss:0.87306
[12]	train-mlogloss:0.86850	eval-mlogloss:0.85852
[13]	train-mlogloss:0.85334	eval-mlogloss:0.84218
[14]	train-mlogloss:0.83830	eval-mlogloss:0.82615
[15]	train-mlogloss:0.82592	eval-mlogloss:0.81403

[I 2025-06-10 11:13:48,059] Trial 21 pruned. Trial was pruned at iteration 16.

[0]	train-mlogloss:1.05657	eval-mlogloss:1.05678
[1]	train-mlogloss:1.03237	eval-mlogloss:1.03651
[2]	train-mlogloss:1.00377	eval-mlogloss:1.01214
[3]	train-mlogloss:0.96175	eval-mlogloss:0.96546
[4]	train-mlogloss:0.94244	eval-mlogloss:0.94949

[I 2025-06-10 11:13:48,189] Trial 22 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.02418	eval-mlogloss:1.02247
[1]	train-mlogloss:0.98330	eval-mlogloss:0.98535
[2]	train-mlogloss:0.92468	eval-mlogloss:0.92202
[3]	train-mlogloss:0.86405	eval-mlogloss:0.85716
[4]	train-mlogloss:0.80959	eval-mlogloss:0.80292

[I 2025-06-10 11:13:48,297] Trial 23 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.97292	eval-mlogloss:0.97203
[1]	train-mlogloss:0.91353	eval-mlogloss:0.91185
[2]	train-mlogloss:0.84296	eval-mlogloss:0.85223
[3]	train-mlogloss:0.74039	eval-mlogloss:0.73509
[4]	train-mlogloss:0.69912	eval-mlogloss:0.70345

[I 2025-06-10 11:13:48,414] Trial 24 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.00518	eval-mlogloss:1.00237
[1]	train-mlogloss:0.96046	eval-mlogloss:0.96480
[2]	train-mlogloss:0.90793	eval-mlogloss:0.91645
[3]	train-mlogloss:0.82671	eval-mlogloss:0.82783
[4]	train-mlogloss:0.79644	eval-mlogloss:0.79906

[I 2025-06-10 11:13:48,558] Trial 25 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.89175	eval-mlogloss:0.88160
[1]	train-mlogloss:0.79399	eval-mlogloss:0.79701

[I 2025-06-10 11:13:48,747] Trial 26 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.87948	eval-mlogloss:0.87398
[1]	train-mlogloss:0.78484	eval-mlogloss:0.78363

[I 2025-06-10 11:13:48,857] Trial 27 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.76423	eval-mlogloss:0.74280

[I 2025-06-10 11:13:48,956] Trial 28 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.83576	eval-mlogloss:0.82634
[1]	train-mlogloss:0.65923	eval-mlogloss:0.63794

[I 2025-06-10 11:13:49,064] Trial 29 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.78072	eval-mlogloss:0.78353
[1]	train-mlogloss:0.61745	eval-mlogloss:0.59352

[I 2025-06-10 11:13:49,168] Trial 30 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.08524	eval-mlogloss:1.08468
[1]	train-mlogloss:1.07773	eval-mlogloss:1.07721
[2]	train-mlogloss:1.06600	eval-mlogloss:1.06538
[3]	train-mlogloss:1.05293	eval-mlogloss:1.05189
[4]	train-mlogloss:1.04028	eval-mlogloss:1.03902
[5]	train-mlogloss:1.02781	eval-mlogloss:1.02596
[6]	train-mlogloss:1.01580	eval-mlogloss:1.01309
[7]	train-mlogloss:1.00379	eval-mlogloss:1.00038
[8]	train-mlogloss:0.99222	eval-mlogloss:0.98800
[9]	train-mlogloss:0.98075	eval-mlogloss:0.97608
[10]	train-mlogloss:0.97056	eval-mlogloss:0.96574
[11]	train-mlogloss:0.95932	eval-mlogloss:0.95426
[12]	train-mlogloss:0.94980	eval-mlogloss:0.94437
[13]	train-mlogloss:0.93884	eval-mlogloss:0.93289
[14]	train-mlogloss:0.92823	eval-mlogloss:0.92139
[15]	train-mlogloss:0.91944	eval-mlogloss:0.91231
[16]	train-mlogloss:0.91069	eval-mlogloss:0.90341
[17]	train-mlogloss:0.90036	eval-mlogloss:0.89268
[18]	train-mlogloss:0.89198	eval-mlogloss:0.88411
[19]	train-mlogloss:0.88298	eval-mlogloss:0.87528
[20]	train-mlogloss:0.87489	eval-mlogloss:0.86683
[21]	train-mlogloss:0.86666	eval-mlogloss:0.85830
[22]	train-mlogloss:0.85717	eval-mlogloss:0.84796
[23]	train-mlogloss:0.84769	eval-mlogloss:0.83815
[24]	train-mlogloss:0.83852	eval-mlogloss:0.82828
[25]	train-mlogloss:0.82943	eval-mlogloss:0.81879
[26]	train-mlogloss:0.82131	eval-mlogloss:0.81007
[27]	train-mlogloss:0.81245	eval-mlogloss:0.80052
[28]	train-mlogloss:0.80381	eval-mlogloss:0.79145
[29]	train-mlogloss:0.79667	eval-mlogloss:0.78389
[30]	train-mlogloss:0.79139	eval-mlogloss:0.77857
[31]	train-mlogloss:0.78474	eval-mlogloss:0.77176
[32]	train-mlogloss:0.77643	eval-mlogloss:0.76311
[33]	train-mlogloss:0.76828	eval-mlogloss:0.75447
[34]	train-mlogloss:0.76190	eval-mlogloss:0.74807
[35]	train-mlogloss:0.75401	eval-mlogloss:0.73941
[36]	train-mlogloss:0.74696	eval-mlogloss:0.73222
[37]	train-mlogloss:0.73911	eval-mlogloss:0.72415
[38]	train-mlogloss:0.73166	eval-mlogloss:0.71607
[39]	train-mlogloss:0.72414	eval-mlogloss:0.70852
[40]	train-mlogloss:0.71798	eval-mlogloss:0.70224
[41]	train-mlogloss:0.71056	eval-mlogloss:0.69445
[42]	train-mlogloss:0.70341	eval-mlogloss:0.68674
[43]	train-mlogloss:0.69619	eval-mlogloss:0.67921
[44]	train-mlogloss:0.69082	eval-mlogloss:0.67367
[45]	train-mlogloss:0.68381	eval-mlogloss:0.66630
[46]	train-mlogloss:0.67697	eval-mlogloss:0.65916
[47]	train-mlogloss:0.67082	eval-mlogloss:0.65292
[48]	train-mlogloss:0.66420	eval-mlogloss:0.64619
[49]	train-mlogloss:0.65753	eval-mlogloss:0.63910
[50]	train-mlogloss:0.65106	eval-mlogloss:0.63205
[51]	train-mlogloss:0.64532	eval-mlogloss:0.62603
[52]	train-mlogloss:0.64107	eval-mlogloss:0.62174
[53]	train-mlogloss:0.63490	eval-mlogloss:0.61519
[54]	train-mlogloss:0.63021	eval-mlogloss:0.61028
[55]	train-mlogloss:0.62507	eval-mlogloss:0.60510
[56]	train-mlogloss:0.62002	eval-mlogloss:0.59981
[57]	train-mlogloss:0.61506	eval-mlogloss:0.59465
[58]	train-mlogloss:0.61050	eval-mlogloss:0.58998
[59]	train-mlogloss:0.60454	eval-mlogloss:0.58371
[60]	train-mlogloss:0.59888	eval-mlogloss:0.57770
[61]	train-mlogloss:0.59410	eval-mlogloss:0.57268
[62]	train-mlogloss:0.58844	eval-mlogloss:0.56668
[63]	train-mlogloss:0.58297	eval-mlogloss:0.56075
[64]	train-mlogloss:0.57744	eval-mlogloss:0.55491
[65]	train-mlogloss:0.57204	eval-mlogloss:0.54937
[66]	train-mlogloss:0.56659	eval-mlogloss:0.54359
[67]	train-mlogloss:0.56249	eval-mlogloss:0.53941
[68]	train-mlogloss:0.55842	eval-mlogloss:0.53527
[69]	train-mlogloss:0.55385	eval-mlogloss:0.53076
[70]	train-mlogloss:0.54930	eval-mlogloss:0.52588
[71]	train-mlogloss:0.54412	eval-mlogloss:0.52019
[72]	train-mlogloss:0.54089	eval-mlogloss:0.51693
[73]	train-mlogloss:0.53591	eval-mlogloss:0.51190
[74]	train-mlogloss:0.53107	eval-mlogloss:0.50687
[75]	train-mlogloss:0.52615	eval-mlogloss:0.50162
[76]	train-mlogloss:0.52299	eval-mlogloss:0.49866
[77]	train-mlogloss:0.51820	eval-mlogloss:0.49383
[78]	train-mlogloss:0.51417	eval-mlogloss:0.48958
[79]	train-mlogloss:0.50948	eval-mlogloss:0.48439
[80]	train-mlogloss:0.50546	eval-mlogloss:0.47989
[81]	train-mlogloss:0.50083	eval-mlogloss:0.47519
[82]	train-mlogloss:0.49645	eval-mlogloss:0.47068
[83]	train-mlogloss:0.49205	eval-mlogloss:0.46588
[84]	train-mlogloss:0.48772	eval-mlogloss:0.46114
[85]	train-mlogloss:0.48475	eval-mlogloss:0.45823
[86]	train-mlogloss:0.48040	eval-mlogloss:0.45336
[87]	train-mlogloss:0.47719	eval-mlogloss:0.45009
[88]	train-mlogloss:0.47341	eval-mlogloss:0.44613
[89]	train-mlogloss:0.46927	eval-mlogloss:0.44163
[90]	train-mlogloss:0.46518	eval-mlogloss:0.43747
[91]	train-mlogloss:0.46175	eval-mlogloss:0.43369
[92]	train-mlogloss:0.45813	eval-mlogloss:0.42977
[93]	train-mlogloss:0.45405	eval-mlogloss:0.42545
[94]	train-mlogloss:0.45012	eval-mlogloss:0.42141
[95]	train-mlogloss:0.44668	eval-mlogloss:0.41778
[96]	train-mlogloss:0.44289	eval-mlogloss:0.41358
[97]	train-mlogloss:0.43905	eval-mlogloss:0.40958
[98]	train-mlogloss:0.43535	eval-mlogloss:0.40566
[99]	train-mlogloss:0.43160	eval-mlogloss:0.40165
[100]	train-mlogloss:0.42869	eval-mlogloss:0.39853
[101]	train-mlogloss:0.42502	eval-mlogloss:0.39477
[102]	train-mlogloss:0.42138	eval-mlogloss:0.39100
[103]	train-mlogloss:0.41867	eval-mlogloss:0.38832
[104]	train-mlogloss:0.41602	eval-mlogloss:0.38565
[105]	train-mlogloss:0.41292	eval-mlogloss:0.38215
[106]	train-mlogloss:0.40947	eval-mlogloss:0.37868
[107]	train-mlogloss:0.40610	eval-mlogloss:0.37510
[108]	train-mlogloss:0.40267	eval-mlogloss:0.37149
[109]	train-mlogloss:0.40011	eval-mlogloss:0.36896
[110]	train-mlogloss:0.39677	eval-mlogloss:0.36524
[111]	train-mlogloss:0.39352	eval-mlogloss:0.36166
[112]	train-mlogloss:0.39121	eval-mlogloss:0.35913
[113]	train-mlogloss:0.38867	eval-mlogloss:0.35643
[114]	train-mlogloss:0.38549	eval-mlogloss:0.35305
[115]	train-mlogloss:0.38241	eval-mlogloss:0.34957
[116]	train-mlogloss:0.37996	eval-mlogloss:0.34713
[117]	train-mlogloss:0.37718	eval-mlogloss:0.34411
[118]	train-mlogloss:0.37423	eval-mlogloss:0.34092
[119]	train-mlogloss:0.37200	eval-mlogloss:0.33856
[120]	train-mlogloss:0.36947	eval-mlogloss:0.33602
[121]	train-mlogloss:0.36649	eval-mlogloss:0.33278
[122]	train-mlogloss:0.36358	eval-mlogloss:0.32966
[123]	train-mlogloss:0.36125	eval-mlogloss:0.32717
[124]	train-mlogloss:0.35906	eval-mlogloss:0.32503
[125]	train-mlogloss:0.35691	eval-mlogloss:0.32269
[126]	train-mlogloss:0.35484	eval-mlogloss:0.32049
[127]	train-mlogloss:0.35261	eval-mlogloss:0.31814
[128]	train-mlogloss:0.34986	eval-mlogloss:0.31511
[129]	train-mlogloss:0.34721	eval-mlogloss:0.31217
[130]	train-mlogloss:0.34467	eval-mlogloss:0.30947
[131]	train-mlogloss:0.34271	eval-mlogloss:0.30732
[132]	train-mlogloss:0.34014	eval-mlogloss:0.30454
[133]	train-mlogloss:0.33854	eval-mlogloss:0.30294
[134]	train-mlogloss:0.33618	eval-mlogloss:0.30028
[135]	train-mlogloss:0.33428	eval-mlogloss:0.29828
[136]	train-mlogloss:0.33188	eval-mlogloss:0.29567
[137]	train-mlogloss:0.32945	eval-mlogloss:0.29304
[138]	train-mlogloss:0.32751	eval-mlogloss:0.29090
[139]	train-mlogloss:0.32566	eval-mlogloss:0.28896
[140]	train-mlogloss:0.32372	eval-mlogloss:0.28665
[141]	train-mlogloss:0.32137	eval-mlogloss:0.28414
[142]	train-mlogloss:0.31920	eval-mlogloss:0.28166
[143]	train-mlogloss:0.31716	eval-mlogloss:0.27922
[144]	train-mlogloss:0.31504	eval-mlogloss:0.27686
[145]	train-mlogloss:0.31281	eval-mlogloss:0.27437
[146]	train-mlogloss:0.31073	eval-mlogloss:0.27207
[147]	train-mlogloss:0.30858	eval-mlogloss:0.26964
[148]	train-mlogloss:0.30664	eval-mlogloss:0.26729
[149]	train-mlogloss:0.30464	eval-mlogloss:0.26498
[150]	train-mlogloss:0.30320	eval-mlogloss:0.26323
[151]	train-mlogloss:0.30124	eval-mlogloss:0.26085
[152]	train-mlogloss:0.29914	eval-mlogloss:0.25850
[153]	train-mlogloss:0.29719	eval-mlogloss:0.25623
[154]	train-mlogloss:0.29518	eval-mlogloss:0.25409
[155]	train-mlogloss:0.29347	eval-mlogloss:0.25216
[156]	train-mlogloss:0.29169	eval-mlogloss:0.25000
[157]	train-mlogloss:0.28973	eval-mlogloss:0.24782
[158]	train-mlogloss:0.28783	eval-mlogloss:0.24568
[159]	train-mlogloss:0.28640	eval-mlogloss:0.24410
[160]	train-mlogloss:0.28461	eval-mlogloss:0.24194
[161]	train-mlogloss:0.28318	eval-mlogloss:0.24034
[162]	train-mlogloss:0.28139	eval-mlogloss:0.23835
[163]	train-mlogloss:0.27999	eval-mlogloss:0.23698
[164]	train-mlogloss:0.27831	eval-mlogloss:0.23491
[165]	train-mlogloss:0.27651	eval-mlogloss:0.23293
[166]	train-mlogloss:0.27526	eval-mlogloss:0.23148
[167]	train-mlogloss:0.27389	eval-mlogloss:0.23008
[168]	train-mlogloss:0.27251	eval-mlogloss:0.22858
[169]	train-mlogloss:0.27080	eval-mlogloss:0.22658
[170]	train-mlogloss:0.26922	eval-mlogloss:0.22470
[171]	train-mlogloss:0.26769	eval-mlogloss:0.22299
[172]	train-mlogloss:0.26653	eval-mlogloss:0.22167
[173]	train-mlogloss:0.26526	eval-mlogloss:0.22032
[174]	train-mlogloss:0.26410	eval-mlogloss:0.21887
[175]	train-mlogloss:0.26283	eval-mlogloss:0.21735
[176]	train-mlogloss:0.26197	eval-mlogloss:0.21642
[177]	train-mlogloss:0.26097	eval-mlogloss:0.21541
[178]	train-mlogloss:0.25945	eval-mlogloss:0.21381
[179]	train-mlogloss:0.25796	eval-mlogloss:0.21211
[180]	train-mlogloss:0.25658	eval-mlogloss:0.21040
[181]	train-mlogloss:0.25511	eval-mlogloss:0.20882
[182]	train-mlogloss:0.25393	eval-mlogloss:0.20767
[183]	train-mlogloss:0.25285	eval-mlogloss:0.20654
[184]	train-mlogloss:0.25174	eval-mlogloss:0.20535
[185]	train-mlogloss:0.25077	eval-mlogloss:0.20424
[186]	train-mlogloss:0.25002	eval-mlogloss:0.20341
[187]	train-mlogloss:0.24925	eval-mlogloss:0.20257
[188]	train-mlogloss:0.24786	eval-mlogloss:0.20096
[189]	train-mlogloss:0.24677	eval-mlogloss:0.19968
[190]	train-mlogloss:0.24545	eval-mlogloss:0.19824
[191]	train-mlogloss:0.24437	eval-mlogloss:0.19701
[192]	train-mlogloss:0.24300	eval-mlogloss:0.19542
[193]	train-mlogloss:0.24232	eval-mlogloss:0.19482
[194]	train-mlogloss:0.24138	eval-mlogloss:0.19373
[195]	train-mlogloss:0.24038	eval-mlogloss:0.19245
[196]	train-mlogloss:0.23919	eval-mlogloss:0.19109
[197]	train-mlogloss:0.23797	eval-mlogloss:0.18965
[198]	train-mlogloss:0.23673	eval-mlogloss:0.18831
[199]	train-mlogloss:0.23586	eval-mlogloss:0.18734
[200]	train-mlogloss:0.23489	eval-mlogloss:0.18620
[201]	train-mlogloss:0.23385	eval-mlogloss:0.18508
[202]	train-mlogloss:0.23261	eval-mlogloss:0.18371
[203]	train-mlogloss:0.23153	eval-mlogloss:0.18242
[204]	train-mlogloss:0.23037	eval-mlogloss:0.18114
[205]	train-mlogloss:0.22921	eval-mlogloss:0.17987
[206]	train-mlogloss:0.22816	eval-mlogloss:0.17873
[207]	train-mlogloss:0.22716	eval-mlogloss:0.17762
[208]	train-mlogloss:0.22640	eval-mlogloss:0.17673
[209]	train-mlogloss:0.22551	eval-mlogloss:0.17583
[210]	train-mlogloss:0.22452	eval-mlogloss:0.17479
[211]	train-mlogloss:0.22371	eval-mlogloss:0.17382
[212]	train-mlogloss:0.22275	eval-mlogloss:0.17268
[213]	train-mlogloss:0.22172	eval-mlogloss:0.17143
[214]	train-mlogloss:0.22081	eval-mlogloss:0.17044
[215]	train-mlogloss:0.22001	eval-mlogloss:0.16953
[216]	train-mlogloss:0.21899	eval-mlogloss:0.16843
[217]	train-mlogloss:0.21797	eval-mlogloss:0.16721
[218]	train-mlogloss:0.21704	eval-mlogloss:0.16621
[219]	train-mlogloss:0.21645	eval-mlogloss:0.16554
[220]	train-mlogloss:0.21542	eval-mlogloss:0.16424
[221]	train-mlogloss:0.21505	eval-mlogloss:0.16387
[222]	train-mlogloss:0.21414	eval-mlogloss:0.16281
[223]	train-mlogloss:0.21399	eval-mlogloss:0.16260
[224]	train-mlogloss:0.21306	eval-mlogloss:0.16154
[225]	train-mlogloss:0.21260	eval-mlogloss:0.16090
[226]	train-mlogloss:0.21175	eval-mlogloss:0.16001
[227]	train-mlogloss:0.21089	eval-mlogloss:0.15909
[228]	train-mlogloss:0.21005	eval-mlogloss:0.15811
[229]	train-mlogloss:0.20956	eval-mlogloss:0.15756
[230]	train-mlogloss:0.20863	eval-mlogloss:0.15648
[231]	train-mlogloss:0.20804	eval-mlogloss:0.15572
[232]	train-mlogloss:0.20767	eval-mlogloss:0.15521
[233]	train-mlogloss:0.20703	eval-mlogloss:0.15451
[234]	train-mlogloss:0.20628	eval-mlogloss:0.15358
[235]	train-mlogloss:0.20565	eval-mlogloss:0.15283
[236]	train-mlogloss:0.20506	eval-mlogloss:0.15213
[237]	train-mlogloss:0.20439	eval-mlogloss:0.15132
[238]	train-mlogloss:0.20375	eval-mlogloss:0.15061
[239]	train-mlogloss:0.20321	eval-mlogloss:0.15005
[240]	train-mlogloss:0.20268	eval-mlogloss:0.14950
[241]	train-mlogloss:0.20259	eval-mlogloss:0.14937
[242]	train-mlogloss:0.20221	eval-mlogloss:0.14891
[243]	train-mlogloss:0.20146	eval-mlogloss:0.14798
[244]	train-mlogloss:0.20115	eval-mlogloss:0.14756
[245]	train-mlogloss:0.20051	eval-mlogloss:0.14683
[246]	train-mlogloss:0.20021	eval-mlogloss:0.14643
[247]	train-mlogloss:0.19986	eval-mlogloss:0.14601
[248]	train-mlogloss:0.19953	eval-mlogloss:0.14564
[249]	train-mlogloss:0.19915	eval-mlogloss:0.14515
[250]	train-mlogloss:0.19835	eval-mlogloss:0.14412
[251]	train-mlogloss:0.19824	eval-mlogloss:0.14398
[252]	train-mlogloss:0.19789	eval-mlogloss:0.14348
[253]	train-mlogloss:0.19781	eval-mlogloss:0.14353
[254]	train-mlogloss:0.19708	eval-mlogloss:0.14276
[255]	train-mlogloss:0.19680	eval-mlogloss:0.14236
[256]	train-mlogloss:0.19652	eval-mlogloss:0.14205
[257]	train-mlogloss:0.19620	eval-mlogloss:0.14160
[258]	train-mlogloss:0.19586	eval-mlogloss:0.14120
[259]	train-mlogloss:0.19550	eval-mlogloss:0.14077
[260]	train-mlogloss:0.19523	eval-mlogloss:0.14048
[261]	train-mlogloss:0.19491	eval-mlogloss:0.14012
[262]	train-mlogloss:0.19464	eval-mlogloss:0.13974
[263]	train-mlogloss:0.19432	eval-mlogloss:0.13937
[264]	train-mlogloss:0.19410	eval-mlogloss:0.13907
[265]	train-mlogloss:0.19373	eval-mlogloss:0.13862
[266]	train-mlogloss:0.19348	eval-mlogloss:0.13823
[267]	train-mlogloss:0.19322	eval-mlogloss:0.13794
[268]	train-mlogloss:0.19291	eval-mlogloss:0.13754
[269]	train-mlogloss:0.19261	eval-mlogloss:0.13720
[270]	train-mlogloss:0.19236	eval-mlogloss:0.13681
[271]	train-mlogloss:0.19209	eval-mlogloss:0.13644
[272]	train-mlogloss:0.19182	eval-mlogloss:0.13607
[273]	train-mlogloss:0.19157	eval-mlogloss:0.13577
[274]	train-mlogloss:0.19130	eval-mlogloss:0.13548
[275]	train-mlogloss:0.19100	eval-mlogloss:0.13515
[276]	train-mlogloss:0.19074	eval-mlogloss:0.13480
[277]	train-mlogloss:0.19047	eval-mlogloss:0.13445
[278]	train-mlogloss:0.19038	eval-mlogloss:0.13445
[279]	train-mlogloss:0.19010	eval-mlogloss:0.13412
[280]	train-mlogloss:0.18983	eval-mlogloss:0.13374
[281]	train-mlogloss:0.18963	eval-mlogloss:0.13348
[282]	train-mlogloss:0.18956	eval-mlogloss:0.13350
[283]	train-mlogloss:0.18930	eval-mlogloss:0.13314
[284]	train-mlogloss:0.18910	eval-mlogloss:0.13284
[285]	train-mlogloss:0.18886	eval-mlogloss:0.13251
[286]	train-mlogloss:0.18866	eval-mlogloss:0.13225
[287]	train-mlogloss:0.18841	eval-mlogloss:0.13197
[288]	train-mlogloss:0.18818	eval-mlogloss:0.13163
[289]	train-mlogloss:0.18793	eval-mlogloss:0.13131
[290]	train-mlogloss:0.18768	eval-mlogloss:0.13096
[291]	train-mlogloss:0.18746	eval-mlogloss:0.13066
[292]	train-mlogloss:0.18735	eval-mlogloss:0.13051
[293]	train-mlogloss:0.18710	eval-mlogloss:0.13023
[294]	train-mlogloss:0.18689	eval-mlogloss:0.12996
[295]	train-mlogloss:0.18631	eval-mlogloss:0.12932
[296]	train-mlogloss:0.18620	eval-mlogloss:0.12933
[297]	train-mlogloss:0.18597	eval-mlogloss:0.12903
[298]	train-mlogloss:0.18578	eval-mlogloss:0.12877
[299]	train-mlogloss:0.18553	eval-mlogloss:0.12843

[I 2025-06-10 11:13:51,058] Trial 31 finished with value: 1.0 and parameters: {'lambda': 4.440215381650762e-07, 'alpha': 4.335471592048758e-05, 'eta': 0.010219866045972841, 'gamma': 6.248490725949232e-08, 'max_depth': 5, 'min_child_weight': 7, 'subsample': 0.862014424387613, 'colsample_bytree': 0.6084237651781361}. Best is trial 0 with value: 1.0.

[0]	train-mlogloss:1.05879	eval-mlogloss:1.05725
[1]	train-mlogloss:1.03906	eval-mlogloss:1.03940
[2]	train-mlogloss:1.00574	eval-mlogloss:1.00457
[3]	train-mlogloss:0.96989	eval-mlogloss:0.96809
[4]	train-mlogloss:0.93617	eval-mlogloss:0.93341

[I 2025-06-10 11:13:51,202] Trial 32 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.02425	eval-mlogloss:1.02080
[1]	train-mlogloss:0.98621	eval-mlogloss:0.98160
[2]	train-mlogloss:0.92828	eval-mlogloss:0.92095
[3]	train-mlogloss:0.86728	eval-mlogloss:0.85820
[4]	train-mlogloss:0.81453	eval-mlogloss:0.80465

[I 2025-06-10 11:13:51,416] Trial 33 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.04910	eval-mlogloss:1.04700
[1]	train-mlogloss:1.02258	eval-mlogloss:1.02057
[2]	train-mlogloss:0.98240	eval-mlogloss:0.97993
[3]	train-mlogloss:0.93984	eval-mlogloss:0.93653
[4]	train-mlogloss:0.90012	eval-mlogloss:0.89591

[I 2025-06-10 11:13:51,523] Trial 34 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.00522	eval-mlogloss:1.00075
[1]	train-mlogloss:0.96226	eval-mlogloss:0.96279

[I 2025-06-10 11:13:51,621] Trial 35 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.98724	eval-mlogloss:0.98042

[I 2025-06-10 11:13:51,720] Trial 36 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.06173	eval-mlogloss:1.06090
[1]	train-mlogloss:1.03983	eval-mlogloss:1.04087
[2]	train-mlogloss:1.00829	eval-mlogloss:1.00688
[3]	train-mlogloss:0.97423	eval-mlogloss:0.97060
[4]	train-mlogloss:0.94236	eval-mlogloss:0.93907

[I 2025-06-10 11:13:51,827] Trial 37 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.99342	eval-mlogloss:0.98853
[1]	train-mlogloss:0.93921	eval-mlogloss:0.93700

[I 2025-06-10 11:13:51,927] Trial 38 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.92178	eval-mlogloss:0.91340
[1]	train-mlogloss:0.84994	eval-mlogloss:0.83895

[I 2025-06-10 11:13:52,027] Trial 39 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.03362	eval-mlogloss:1.03086

[I 2025-06-10 11:13:52,189] Trial 40 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.08088	eval-mlogloss:1.08014
[1]	train-mlogloss:1.07100	eval-mlogloss:1.07029
[2]	train-mlogloss:1.05551	eval-mlogloss:1.05464
[3]	train-mlogloss:1.03846	eval-mlogloss:1.03735
[4]	train-mlogloss:1.02202	eval-mlogloss:1.02060
[5]	train-mlogloss:1.00591	eval-mlogloss:1.00373
[6]	train-mlogloss:0.99050	eval-mlogloss:0.98720
[7]	train-mlogloss:0.97525	eval-mlogloss:0.97116
[8]	train-mlogloss:0.96061	eval-mlogloss:0.95549
[9]	train-mlogloss:0.94610	eval-mlogloss:0.94040
[10]	train-mlogloss:0.93328	eval-mlogloss:0.92720
[11]	train-mlogloss:0.91920	eval-mlogloss:0.91279
[12]	train-mlogloss:0.90745	eval-mlogloss:0.90031
[13]	train-mlogloss:0.89391	eval-mlogloss:0.88611
[14]	train-mlogloss:0.88082	eval-mlogloss:0.87189
[15]	train-mlogloss:0.87007	eval-mlogloss:0.86076
[16]	train-mlogloss:0.85933	eval-mlogloss:0.84982

[I 2025-06-10 11:13:52,375] Trial 41 pruned. Trial was pruned at iteration 16.

[0]	train-mlogloss:1.07819	eval-mlogloss:1.07733
[1]	train-mlogloss:1.06685	eval-mlogloss:1.06635
[2]	train-mlogloss:1.04917	eval-mlogloss:1.04803
[3]	train-mlogloss:1.02996	eval-mlogloss:1.02859
[4]	train-mlogloss:1.01134	eval-mlogloss:1.00947
[5]	train-mlogloss:0.99339	eval-mlogloss:0.99069
[6]	train-mlogloss:0.97600	eval-mlogloss:0.97199
[7]	train-mlogloss:0.95882	eval-mlogloss:0.95400
[8]	train-mlogloss:0.94259	eval-mlogloss:0.93667
[9]	train-mlogloss:0.92638	eval-mlogloss:0.91980
[10]	train-mlogloss:0.91206	eval-mlogloss:0.90519
[11]	train-mlogloss:0.89641	eval-mlogloss:0.88913
[12]	train-mlogloss:0.88345	eval-mlogloss:0.87540
[13]	train-mlogloss:0.86860	eval-mlogloss:0.85980
[14]	train-mlogloss:0.85413	eval-mlogloss:0.84403
[15]	train-mlogloss:0.84229	eval-mlogloss:0.83176

[I 2025-06-10 11:13:52,536] Trial 42 pruned. Trial was pruned at iteration 16.

[0]	train-mlogloss:1.06613	eval-mlogloss:1.06468
[1]	train-mlogloss:1.05047	eval-mlogloss:1.04784
[2]	train-mlogloss:1.02332	eval-mlogloss:1.01930
[3]	train-mlogloss:0.99342	eval-mlogloss:0.98878

[I 2025-06-10 11:13:52,642] Trial 43 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:0.79068	eval-mlogloss:0.78293

[I 2025-06-10 11:13:52,798] Trial 44 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.77678	eval-mlogloss:0.76041
[1]	train-mlogloss:0.67981	eval-mlogloss:0.65689

[I 2025-06-10 11:13:52,906] Trial 45 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.03653	eval-mlogloss:1.03201
[1]	train-mlogloss:1.00811	eval-mlogloss:0.99689

[I 2025-06-10 11:13:53,010] Trial 46 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:0.85258	eval-mlogloss:0.85538

[I 2025-06-10 11:13:53,113] Trial 47 pruned. Trial was pruned at iteration 1.

[0]	train-mlogloss:1.03591	eval-mlogloss:1.03259
[1]	train-mlogloss:0.99706	eval-mlogloss:0.99965
[2]	train-mlogloss:0.94607	eval-mlogloss:0.94582
[3]	train-mlogloss:0.89410	eval-mlogloss:0.89185
[4]	train-mlogloss:0.84733	eval-mlogloss:0.84325

[I 2025-06-10 11:13:53,229] Trial 48 pruned. Trial was pruned at iteration 4.

[0]	train-mlogloss:1.08528	eval-mlogloss:1.08477
[1]	train-mlogloss:1.07223	eval-mlogloss:1.07086
[2]	train-mlogloss:1.05885	eval-mlogloss:1.05686
[3]	train-mlogloss:1.04558	eval-mlogloss:1.04321
[4]	train-mlogloss:1.03313	eval-mlogloss:1.03041
[5]	train-mlogloss:1.02039	eval-mlogloss:1.01690
[6]	train-mlogloss:1.00851	eval-mlogloss:1.00437
[7]	train-mlogloss:0.99700	eval-mlogloss:0.99174
[8]	train-mlogloss:0.98526	eval-mlogloss:0.97914
[9]	train-mlogloss:0.97369	eval-mlogloss:0.96668
[10]	train-mlogloss:0.96233	eval-mlogloss:0.95499
[11]	train-mlogloss:0.95119	eval-mlogloss:0.94319
[12]	train-mlogloss:0.94037	eval-mlogloss:0.93186
[13]	train-mlogloss:0.92945	eval-mlogloss:0.92060
[14]	train-mlogloss:0.91901	eval-mlogloss:0.90936
[15]	train-mlogloss:0.90851	eval-mlogloss:0.89813
[16]	train-mlogloss:0.89814	eval-mlogloss:0.88714
[17]	train-mlogloss:0.88835	eval-mlogloss:0.87669
[18]	train-mlogloss:0.87844	eval-mlogloss:0.86631
[19]	train-mlogloss:0.86856	eval-mlogloss:0.85629
[20]	train-mlogloss:0.85888	eval-mlogloss:0.84605
[21]	train-mlogloss:0.85037	eval-mlogloss:0.83673
[22]	train-mlogloss:0.84081	eval-mlogloss:0.82668
[23]	train-mlogloss:0.83144	eval-mlogloss:0.81684
[24]	train-mlogloss:0.82218	eval-mlogloss:0.80715
[25]	train-mlogloss:0.81325	eval-mlogloss:0.79770
[26]	train-mlogloss:0.80453	eval-mlogloss:0.78838
[27]	train-mlogloss:0.79573	eval-mlogloss:0.77930
[28]	train-mlogloss:0.78717	eval-mlogloss:0.77017
[29]	train-mlogloss:0.77861	eval-mlogloss:0.76100
[30]	train-mlogloss:0.77037	eval-mlogloss:0.75268
[31]	train-mlogloss:0.76215	eval-mlogloss:0.74388
[32]	train-mlogloss:0.75428	eval-mlogloss:0.73580
[33]	train-mlogloss:0.74675	eval-mlogloss:0.72738
[34]	train-mlogloss:0.73891	eval-mlogloss:0.71918
[35]	train-mlogloss:0.73150	eval-mlogloss:0.71129
[36]	train-mlogloss:0.72391	eval-mlogloss:0.70342
[37]	train-mlogloss:0.71649	eval-mlogloss:0.69581
[38]	train-mlogloss:0.70941	eval-mlogloss:0.68854
[39]	train-mlogloss:0.70196	eval-mlogloss:0.68083
[40]	train-mlogloss:0.69481	eval-mlogloss:0.67364
[41]	train-mlogloss:0.68774	eval-mlogloss:0.66595
[42]	train-mlogloss:0.68084	eval-mlogloss:0.65869
[43]	train-mlogloss:0.67395	eval-mlogloss:0.65145
[44]	train-mlogloss:0.66693	eval-mlogloss:0.64425
[45]	train-mlogloss:0.66012	eval-mlogloss:0.63730
[46]	train-mlogloss:0.65334	eval-mlogloss:0.63030
[47]	train-mlogloss:0.64688	eval-mlogloss:0.62348
[48]	train-mlogloss:0.64032	eval-mlogloss:0.61649
[49]	train-mlogloss:0.63386	eval-mlogloss:0.60987
[50]	train-mlogloss:0.62757	eval-mlogloss:0.60306
[51]	train-mlogloss:0.62142	eval-mlogloss:0.59637
[52]	train-mlogloss:0.61543	eval-mlogloss:0.58978
[53]	train-mlogloss:0.60948	eval-mlogloss:0.58327
[54]	train-mlogloss:0.60343	eval-mlogloss:0.57706
[55]	train-mlogloss:0.59750	eval-mlogloss:0.57096
[56]	train-mlogloss:0.59176	eval-mlogloss:0.56497
[57]	train-mlogloss:0.58610	eval-mlogloss:0.55938
[58]	train-mlogloss:0.58047	eval-mlogloss:0.55368
[59]	train-mlogloss:0.57492	eval-mlogloss:0.54761
[60]	train-mlogloss:0.56939	eval-mlogloss:0.54208
[61]	train-mlogloss:0.56396	eval-mlogloss:0.53623
[62]	train-mlogloss:0.55849	eval-mlogloss:0.53048
[63]	train-mlogloss:0.55342	eval-mlogloss:0.52507
[64]	train-mlogloss:0.54824	eval-mlogloss:0.51959

[I 2025-06-10 11:13:53,742] Trial 49 pruned. Trial was pruned at iteration 64.

Best trial: {'lambda': 0.00013695093332539675, 'alpha': 0.0008298234829026117, 'eta': 0.1824635846276565, 'gamma': 0.0006890317133960559, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.4219159808455654, 'colsample_bytree': 0.56114666874105}
Best accuracy: 1.0

In [35]:
! pip install optuna-integration[xgboost]

Defaulting to user installation because normal site-packages is not writeable
Collecting optuna-integration[xgboost]
  Downloading optuna_integration-4.3.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: optuna in c:\users\admin\appdata\roaming\python\python313\site-packages (from optuna-integration[xgboost]) (4.3.0)
Requirement already satisfied: xgboost in c:\users\admin\appdata\roaming\python\python313\site-packages (from optuna-integration[xgboost]) (3.0.0)
Requirement already satisfied: alembic>=1.5.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from optuna->optuna-integration[xgboost]) (1.16.1)
Requirement already satisfied: colorlog in c:\users\admin\appdata\roaming\python\python313\site-packages (from optuna->optuna-integration[xgboost]) (6.9.0)
Requirement already satisfied: numpy in c:\users\admin\appdata\roaming\python\python313\site-packages (from optuna->optuna-integration[xgboost]) (2.2.1)
Requirement already satisfied: packaging>=20.0 in c:\users\admin\appdata\roaming\python\python313\site-packages (from optuna->optuna-integration[xgboost]) (24.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in c:\users\admin\appdata\roaming\python\python313\site-packages (from optuna->optuna-integration[xgboost]) (2.0.41)
Requirement already satisfied: tqdm in c:\users\admin\appdata\roaming\python\python313\site-packages (from optuna->optuna-integration[xgboost]) (4.67.1)
Requirement already satisfied: PyYAML in c:\users\admin\appdata\roaming\python\python313\site-packages (from optuna->optuna-integration[xgboost]) (6.0.2)
Requirement already satisfied: Mako in c:\users\admin\appdata\roaming\python\python313\site-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in c:\users\admin\appdata\roaming\python\python313\site-packages (from alembic>=1.5.0->optuna->optuna-integration[xgboost]) (4.12.2)
Requirement already satisfied: greenlet>=1 in c:\users\admin\appdata\roaming\python\python313\site-packages (from sqlalchemy>=1.4.2->optuna->optuna-integration[xgboost]) (3.2.3)
Requirement already satisfied: colorama in c:\users\admin\appdata\roaming\python\python313\site-packages (from colorlog->optuna->optuna-integration[xgboost]) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in c:\users\admin\appdata\roaming\python\python313\site-packages (from Mako->alembic>=1.5.0->optuna->optuna-integration[xgboost]) (2.0.1)
Requirement already satisfied: scipy in c:\users\admin\appdata\roaming\python\python313\site-packages (from xgboost->optuna-integration[xgboost]) (1.15.1)
Downloading optuna_integration-4.3.0-py3-none-any.whl (98 kB)
Installing collected packages: optuna-integration
Successfully installed optuna-integration-4.3.0

In [37]:
from optuna.visualization import plot_intermediate_values

# 1. Plot intermediate values during the trials
plot_intermediate_values(study).show()